# Lab 1: ARIMA models

Team member names: Eric French (Civil), Dylan Hubl (ESRM), Miranda Mudge (Molecular & Cell Bio)

# Data

Bristol Bay Data. Discuss what part of the data set you will work with.

# Question your team will address

What will your team do with the data? You can do many things with the data. The only constraints are that you

-   fit ARIMA models (note you'll want to log the abundance data). You can fit other models in addition ot ARIMA if you want.
-   do diagnostics for ARIMA models
-   make forecasts
-   test how good your forecasts or compare forecasts (many options here)

Example, "Our team decided to compare the accuracy of forecasts using best fit ARIMA models for pink salmon using 4 regions in the Ruggerone & Irvine data. Our question is whether forecast accuracy is different for different regions."

# Method you will use

## Initial plan

Describe what you plan to do to address your question. Note this example is with Ruggerone & Irvine data but your team will use the Bristol Bay data.

Fit ARIMA Models to 1960-2010 data on 4 yr old fish in the Wood and Ugashik systems. Then forecast to 2020. Split up the 1.3 and 2.2 age groups and compare. Measure one-step-ahead accuracy of training data and accuracy of forecast. We will measure accuracy by the comparing the RMS error of each model.

Example, "We will fit ARIMA models to 1960-1980 data on pink salmon in 2 regions in Alaska and 2 regions in E Asia. We will make 1981-1985 forecasts (5 year) and compare the accuracy of the forecasts to the actual values. We will measure accuracy with mean squared error. We will use the forecast package to fit the ARIMA models."

## What you actually did

Example, "We were able to do our plan fairly quickly, so after writing the basic code, we divided up all 12 regions in Ruggerone & Irvine and each team member did 4 regions. We compared the accuracy of forecasts for different time periods using 20-years for training and 5-year forecasts each time. We compared the RMSE, MAE, and MAPE accuracy measures."

# Diagnostics and preliminary exploration

## Plot the data

Plot the data and discuss any obvious problems with stationarity from your visual test.

## Use ACF and PACF

Use the ACF and PACF plots to explore the time series. What did you learn? Also try decomposition.

## Test for stationarity

Run tests and discuss any stationarity issues and how these were addressed.

# Results

# Discussion

# Description of each team member's contributions

Example: "All team members helped decide on the goal and ran the analyses for the individual regions. Team members 2 & 3 wrote most of the code for the analysis of the regions. Team member 4 researched approaches for measuring accuracy of forecasts in [Hyndman & Athanasopoulos[OTexts.com/fpp2] and team member 2 added code for that to the methods. Team member 4 also researched tests for stationarity and worked with team member 2 to code that up. Team member 1 worked on the plotting section of the report using and adapting code that team member 3 wrote. All team members helped edit the report and wrote the discussion together."
