<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Eric French (Civil), Dylan Hubl (ESRM), Miranda Mudge (Molecular &amp; Cell Bio)">

<title>Fish 550 Spring 2023 - 4&nbsp; Team 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../Lab-1/Final_Write_ups/Lab-1-team-3_final.html" rel="next">
<link href="../../Lab-1/Final_Write_ups/Lab-1-team-1_final.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Team 2</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Fish 550 Spring 2023</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/atsa-es/fish550-2023" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Labs</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Forecasting with ARIMA models</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Lab-1/Lab1-ARIMA.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Lab Intro</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Lab-1/Final_Write_ups/Lab-1-team-1_final.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Team 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Lab-1/Final_Write_ups/Lab-1-team-2_final.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Team 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Lab-1/Final_Write_ups/Lab-1-team-3_final.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Team 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Lab-1/Final_Write_ups/Lab-1-team-4_final.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Team 4</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Analyzing multivariate salmon data with MARSS</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../Lab-2/Lab2-MARSS.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Lab Intro</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#lab-1-arima-models" id="toc-lab-1-arima-models" class="nav-link active" data-scroll-target="#lab-1-arima-models"><span class="toc-section-number">5</span>  Lab 1: ARIMA models</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="toc-section-number">6</span>  Data</a></li>
  <li><a href="#question-your-team-will-address" id="toc-question-your-team-will-address" class="nav-link" data-scroll-target="#question-your-team-will-address"><span class="toc-section-number">7</span>  Question your team will address</a></li>
  <li><a href="#method-you-will-use" id="toc-method-you-will-use" class="nav-link" data-scroll-target="#method-you-will-use"><span class="toc-section-number">8</span>  Method you will use</a>
  <ul class="collapse">
  <li><a href="#initial-plan" id="toc-initial-plan" class="nav-link" data-scroll-target="#initial-plan"><span class="toc-section-number">8.1</span>  Initial plan</a></li>
  <li><a href="#what-you-actually-did" id="toc-what-you-actually-did" class="nav-link" data-scroll-target="#what-you-actually-did"><span class="toc-section-number">8.2</span>  What you actually did</a></li>
  </ul></li>
  <li><a href="#diagnostics-and-preliminary-exploration" id="toc-diagnostics-and-preliminary-exploration" class="nav-link" data-scroll-target="#diagnostics-and-preliminary-exploration"><span class="toc-section-number">9</span>  Diagnostics and preliminary exploration</a>
  <ul class="collapse">
  <li><a href="#plot-the-data" id="toc-plot-the-data" class="nav-link" data-scroll-target="#plot-the-data"><span class="toc-section-number">9.1</span>  Plot the data</a>
  <ul class="collapse">
  <li><a href="#ugashik-region" id="toc-ugashik-region" class="nav-link" data-scroll-target="#ugashik-region"><span class="toc-section-number">9.1.1</span>  Ugashik Region</a></li>
  <li><a href="#wood-region" id="toc-wood-region" class="nav-link" data-scroll-target="#wood-region"><span class="toc-section-number">9.1.2</span>  Wood Region</a></li>
  <li><a href="#kvichak-region" id="toc-kvichak-region" class="nav-link" data-scroll-target="#kvichak-region"><span class="toc-section-number">9.1.3</span>  Kvichak Region</a></li>
  </ul></li>
  <li><a href="#testing-for-stationarity" id="toc-testing-for-stationarity" class="nav-link" data-scroll-target="#testing-for-stationarity"><span class="toc-section-number">9.2</span>  Testing for Stationarity</a>
  <ul class="collapse">
  <li><a href="#ugashik" id="toc-ugashik" class="nav-link" data-scroll-target="#ugashik"><span class="toc-section-number">9.2.1</span>  Ugashik</a></li>
  <li><a href="#wood" id="toc-wood" class="nav-link" data-scroll-target="#wood"><span class="toc-section-number">9.2.2</span>  Wood</a></li>
  <li><a href="#kvichak" id="toc-kvichak" class="nav-link" data-scroll-target="#kvichak"><span class="toc-section-number">9.2.3</span>  Kvichak</a></li>
  </ul></li>
  <li><a href="#acf-and-pacf" id="toc-acf-and-pacf" class="nav-link" data-scroll-target="#acf-and-pacf"><span class="toc-section-number">9.3</span>  ACF and PACF</a>
  <ul class="collapse">
  <li><a href="#ugashik-1" id="toc-ugashik-1" class="nav-link" data-scroll-target="#ugashik-1"><span class="toc-section-number">9.3.1</span>  Ugashik</a></li>
  <li><a href="#wood-1" id="toc-wood-1" class="nav-link" data-scroll-target="#wood-1"><span class="toc-section-number">9.3.2</span>  Wood</a></li>
  <li><a href="#kvichak-1" id="toc-kvichak-1" class="nav-link" data-scroll-target="#kvichak-1"><span class="toc-section-number">9.3.3</span>  Kvichak</a></li>
  </ul></li>
  <li><a href="#checking-residuals" id="toc-checking-residuals" class="nav-link" data-scroll-target="#checking-residuals"><span class="toc-section-number">9.4</span>  Checking Residuals</a>
  <ul class="collapse">
  <li><a href="#ugashik-2" id="toc-ugashik-2" class="nav-link" data-scroll-target="#ugashik-2"><span class="toc-section-number">9.4.1</span>  Ugashik</a></li>
  <li><a href="#wood-2" id="toc-wood-2" class="nav-link" data-scroll-target="#wood-2"><span class="toc-section-number">9.4.2</span>  Wood</a></li>
  <li><a href="#kvichak-2" id="toc-kvichak-2" class="nav-link" data-scroll-target="#kvichak-2"><span class="toc-section-number">9.4.3</span>  Kvichak</a></li>
  </ul></li>
  <li><a href="#fit-models-to-the-training-data" id="toc-fit-models-to-the-training-data" class="nav-link" data-scroll-target="#fit-models-to-the-training-data"><span class="toc-section-number">9.5</span>  Fit Models to the training data</a>
  <ul class="collapse">
  <li><a href="#ugashik-3" id="toc-ugashik-3" class="nav-link" data-scroll-target="#ugashik-3"><span class="toc-section-number">9.5.1</span>  Ugashik</a></li>
  <li><a href="#wood-3" id="toc-wood-3" class="nav-link" data-scroll-target="#wood-3"><span class="toc-section-number">9.5.2</span>  Wood</a></li>
  <li><a href="#kvichak-3" id="toc-kvichak-3" class="nav-link" data-scroll-target="#kvichak-3"><span class="toc-section-number">9.5.3</span>  Kvichak</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="toc-section-number">10</span>  Results</a>
  <ul class="collapse">
  <li><a href="#plotting-best-fit-results-and-determining-model-accuracy" id="toc-plotting-best-fit-results-and-determining-model-accuracy" class="nav-link" data-scroll-target="#plotting-best-fit-results-and-determining-model-accuracy"><span class="toc-section-number">10.1</span>  Plotting Best Fit Results and Determining Model Accuracy</a>
  <ul class="collapse">
  <li><a href="#ugashik-1.3-starting-from-1980" id="toc-ugashik-1.3-starting-from-1980" class="nav-link" data-scroll-target="#ugashik-1.3-starting-from-1980"><span class="toc-section-number">10.1.1</span>  Ugashik 1.3, Starting from 1980</a></li>
  <li><a href="#ugashik-2.2" id="toc-ugashik-2.2" class="nav-link" data-scroll-target="#ugashik-2.2"><span class="toc-section-number">10.1.2</span>  Ugashik 2.2</a></li>
  <li><a href="#wood-1.3" id="toc-wood-1.3" class="nav-link" data-scroll-target="#wood-1.3"><span class="toc-section-number">10.1.3</span>  Wood 1.3</a></li>
  <li><a href="#kvichak-2.2" id="toc-kvichak-2.2" class="nav-link" data-scroll-target="#kvichak-2.2"><span class="toc-section-number">10.1.4</span>  Kvichak 2.2</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="toc-section-number">11</span>  Discussion</a></li>
  <li><a href="#description-of-each-team-members-contributions" id="toc-description-of-each-team-members-contributions" class="nav-link" data-scroll-target="#description-of-each-team-members-contributions"><span class="toc-section-number">12</span>  Description of each team member’s contributions</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/atsa-es/fish550-2023/edit/main/Lab-1/Final_Write_ups/Lab-1-team-2_final.Rmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/atsa-es/fish550-2023/blob/main/Lab-1/Final_Write_ups/Lab-1-team-2_final.Rmd" class="toc-action">View source</a></p><p><a href="https://github.com/atsa-es/fish550-2023/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title d-none d-lg-block"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Team 2</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
<p class="subtitle lead">Lab 1 Forecasting with ARIMA models</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Eric French (Civil), Dylan Hubl (ESRM), Miranda Mudge (Molecular &amp; Cell Bio) </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="lab-1-arima-models" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Lab 1: ARIMA models</h1>
<p>Team member names: Eric French (Civil), Dylan Hubl (ESRM), Miranda Mudge (Molecular &amp; Cell Bio)</p>
</section>
<section id="data" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Data</h1>
<p>We will be working with the Bristol Bay data set. Our focus will be on 4-year-old Sockeye in the Wood, Kvichak, and Ugashik regions.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors
Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo 


Attaching package: 'zoo'


The following objects are masked from 'package:base':

    as.Date, as.Date.numeric</code></pre>
</div>
</div>
</section>
<section id="question-your-team-will-address" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Question your team will address</h1>
<p>Our group decided to compare how accurate the forecasts of best fit ARIMA models were for the populations of 4 year old salmon (1.3 and 2.2 age groups) were in the Wood, Kvichak, and Ugashik regions of the Bristol Bay data. Our questions were the following:</p>
<ol type="1">
<li><p>What kind of ARIMA model best fits the population in each chosen region and age group of sockeye salmon?</p></li>
<li><p>Which populations of salmon can be better forecast using ARIMA modeling? Those that have spent 2 years in the ocean or 3?</p></li>
<li><p>Is there regional variation in the population changes of 4-year-old salmon?</p></li>
</ol>
</section>
<section id="method-you-will-use" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Method you will use</h1>
<p>We will fit ARIMA models to each region and age group and compare the model structures. Then compare the forecast results of each model and comment on the accuracy of each.</p>
<section id="initial-plan" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="initial-plan"><span class="header-section-number">8.1</span> Initial plan</h2>
<p>Using the forecast package, we plan to fit ARIMA models to the 1960-2010 data on 4 yr old fish in the Wood and Ugashik systems. Then forecast to 2020. We will separate the fish by time spent in freshwater and time in the ocean. These age groups are labeled 1.3 (1 year in freshwater, 3 years in the ocean) and 2.2 (2 years in freshwater, 2 years in the ocean). We will measure accuracy by the comparing the RMS error of each model.</p>
</section>
<section id="what-you-actually-did" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="what-you-actually-did"><span class="header-section-number">8.2</span> What you actually did</h2>
<p>We were able to enact our plan with a few modifications. Instead of modeling all the 4 year old salmon together, we separated and compared them by age group from the outset. Additionally, we added the Kvichak region to our analysis. We also examined the accuracy of the forecast if we removed the years prior to 1980 from the training data for the 1.3 age group in the Ugashik river. We did this as there was increased variance in the observed data if we included 1960 - 1980. We thought that removing the variance may improve the accuracy of the forecast, so we fit a second model to the data starting at the year 1980 and compared its forecast to the original model’s.</p>
</section>
</section>
<section id="diagnostics-and-preliminary-exploration" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Diagnostics and preliminary exploration</h1>
<section id="plot-the-data" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="plot-the-data"><span class="header-section-number">9.1</span> Plot the data</h2>
<section id="ugashik-region" class="level3" data-number="9.1.1">
<h3 data-number="9.1.1" class="anchored" data-anchor-id="ugashik-region"><span class="header-section-number">9.1.1</span> Ugashik Region</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-2-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-2-3.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="wood-region" class="level3" data-number="9.1.2">
<h3 data-number="9.1.2" class="anchored" data-anchor-id="wood-region"><span class="header-section-number">9.1.2</span> Wood Region</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="kvichak-region" class="level3" data-number="9.1.3">
<h3 data-number="9.1.3" class="anchored" data-anchor-id="kvichak-region"><span class="header-section-number">9.1.3</span> Kvichak Region</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Uvashik: Upon observing the 1.3 time series, there is a clear outlier value at 1977. To remove the negative value, we re-plotted the data starting at 1980 instead of 1967. The new time series seems to show variance around a mean of 7. The 2.2 group appears to show variance around a mean of 5. Differencing the data will likely show stationarity</p>
<p>Wood: The 1.3 age group appears to have a positive trend, so it is likely not stationary. It could be stationary around a trend. The 2.2 age group does not seem to have any trends, and could be stationary around a mean of 4.</p>
<p>Kvichak: There is another negative outlier in the 1.3 age group, otherwise the data appears to be stationary around a mean of 7. We will have to see how much influence the outlier has on the ARIMA model. The 2.2 age group does not show any obvious trends and seems to be stationary around a mean of 7.</p>
</section>
</section>
<section id="testing-for-stationarity" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="testing-for-stationarity"><span class="header-section-number">9.2</span> Testing for Stationarity</h2>
<section id="ugashik" class="level3" data-number="9.2.1">
<h3 data-number="9.2.1" class="anchored" data-anchor-id="ugashik"><span class="header-section-number">9.2.1</span> Ugashik</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Augmented Dickey-Fuller Test

data:  Ugashik_1.3.ts
Dickey-Fuller = -3.1174, Lag order = 3, p-value = 0.1236
alternative hypothesis: stationary</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    KPSS Test for Level Stationarity

data:  Ugashik_1.3.ts
KPSS Level = 0.54744, Truncation lag parameter = 3, p-value = 0.03098</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in tseries::kpss.test(Ugashik_1.3.ts, null = "Trend"): p-value greater
than printed p-value</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    KPSS Test for Trend Stationarity

data:  Ugashik_1.3.ts
KPSS Trend = 0.075997, Truncation lag parameter = 3, p-value = 0.1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Augmented Dickey-Fuller Test

data:  Ugashik_1.3.ts_out
Dickey-Fuller = -3.4337, Lag order = 3, p-value = 0.06582
alternative hypothesis: stationary</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in tseries::kpss.test(Ugashik_1.3.ts_out, null = "Level"): p-value
greater than printed p-value</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    KPSS Test for Level Stationarity

data:  Ugashik_1.3.ts_out
KPSS Level = 0.26391, Truncation lag parameter = 3, p-value = 0.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in tseries::kpss.test(Ugashik_1.3.ts_out, null = "Trend"): p-value
greater than printed p-value</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    KPSS Test for Trend Stationarity

data:  Ugashik_1.3.ts_out
KPSS Trend = 0.065518, Truncation lag parameter = 3, p-value = 0.1</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Augmented Dickey-Fuller Test

data:  Ugashik_2.2.ts
Dickey-Fuller = -2.0383, Lag order = 3, p-value = 0.5592
alternative hypothesis: stationary</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in tseries::kpss.test(Ugashik_2.2.ts, null = "Level"): p-value greater
than printed p-value</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    KPSS Test for Level Stationarity

data:  Ugashik_2.2.ts
KPSS Level = 0.21297, Truncation lag parameter = 3, p-value = 0.1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    KPSS Test for Trend Stationarity

data:  Ugashik_2.2.ts
KPSS Trend = 0.184, Truncation lag parameter = 3, p-value = 0.022</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Stationairity test for the full Ugashik 1.3 group were in disagreement indicating that a single difference should be taken to get them to agree on stationairity. The same is true for the 2.2 group, we again see disagreement in the tests. The truncated dataset of the 1.3 group shows full agreement on non-stationairity. Thus a first difference needs to be taken on all of them.</p>
</section>
<section id="wood" class="level3" data-number="9.2.2">
<h3 data-number="9.2.2" class="anchored" data-anchor-id="wood"><span class="header-section-number">9.2.2</span> Wood</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Augmented Dickey-Fuller Test

data:  Wood_1.3.ts
Dickey-Fuller = -3.1466, Lag order = 3, p-value = 0.1118
alternative hypothesis: stationary</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in tseries::adf.test(Wood_1.3.ts, k = 0): p-value smaller than printed
p-value</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Augmented Dickey-Fuller Test

data:  Wood_1.3.ts
Dickey-Fuller = -6.5462, Lag order = 0, p-value = 0.01
alternative hypothesis: stationary</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in tseries::kpss.test(Wood_1.3.ts, null = "Level"): p-value smaller
than printed p-value</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    KPSS Test for Level Stationarity

data:  Wood_1.3.ts
KPSS Level = 1.1774, Truncation lag parameter = 3, p-value = 0.01</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    KPSS Test for Trend Stationarity

data:  Wood_1.3.ts
KPSS Trend = 0.14659, Truncation lag parameter = 3, p-value = 0.04951</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Augmented Dickey-Fuller Test

data:  Wood_2.2.ts
Dickey-Fuller = -3.7358, Lag order = 3, p-value = 0.02957
alternative hypothesis: stationary</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in tseries::adf.test(Wood_2.2.ts, k = 0): p-value smaller than printed
p-value</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Augmented Dickey-Fuller Test

data:  Wood_2.2.ts
Dickey-Fuller = -7.91, Lag order = 0, p-value = 0.01
alternative hypothesis: stationary</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in tseries::kpss.test(Wood_2.2.ts, null = "Level"): p-value greater
than printed p-value</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    KPSS Test for Level Stationarity

data:  Wood_2.2.ts
KPSS Level = 0.076509, Truncation lag parameter = 3, p-value = 0.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in tseries::kpss.test(Wood_2.2.ts, null = "Trend"): p-value greater
than printed p-value</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    KPSS Test for Trend Stationarity

data:  Wood_2.2.ts
KPSS Trend = 0.058765, Truncation lag parameter = 3, p-value = 0.1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>The Wood River 1.3 showed disagreement in the outcome of the stationairity tests this indicates that a difference is required to reach stationairity. The ndiff() function disagrees based on test used but the kpss test indicates a single differencing is required. In contrast the Wood River 2.2 group has full agreement from all tests for stationairity. The ndiff() function also indicates that no differencing is required for this dataset.</p>
</section>
<section id="kvichak" class="level3" data-number="9.2.3">
<h3 data-number="9.2.3" class="anchored" data-anchor-id="kvichak"><span class="header-section-number">9.2.3</span> Kvichak</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Augmented Dickey-Fuller Test

data:  Kvichak_1.3.ts
Dickey-Fuller = -3.5126, Lag order = 3, p-value = 0.04835
alternative hypothesis: stationary</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in tseries::adf.test(Kvichak_1.3.ts, k = 0): p-value smaller than
printed p-value</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Augmented Dickey-Fuller Test

data:  Kvichak_1.3.ts
Dickey-Fuller = -7.0898, Lag order = 0, p-value = 0.01
alternative hypothesis: stationary</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in tseries::kpss.test(Kvichak_1.3.ts, null = "Level"): p-value smaller
than printed p-value</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    KPSS Test for Level Stationarity

data:  Kvichak_1.3.ts
KPSS Level = 0.87527, Truncation lag parameter = 3, p-value = 0.01</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    KPSS Test for Trend Stationarity

data:  Kvichak_1.3.ts
KPSS Trend = 0.16823, Truncation lag parameter = 3, p-value = 0.03147</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Augmented Dickey-Fuller Test

data:  Kvichak_2.2.ts
Dickey-Fuller = -3.0401, Lag order = 3, p-value = 0.1548
alternative hypothesis: stationary</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in tseries::adf.test(Kvichak_2.2.ts, k = 0): p-value smaller than
printed p-value</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Augmented Dickey-Fuller Test

data:  Kvichak_2.2.ts
Dickey-Fuller = -5.4257, Lag order = 0, p-value = 0.01
alternative hypothesis: stationary</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in tseries::kpss.test(Kvichak_2.2.ts, null = "Level"): p-value greater
than printed p-value</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    KPSS Test for Level Stationarity

data:  Kvichak_2.2.ts
KPSS Level = 0.33673, Truncation lag parameter = 3, p-value = 0.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in tseries::kpss.test(Kvichak_2.2.ts, null = "Trend"): p-value greater
than printed p-value</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    KPSS Test for Trend Stationarity

data:  Kvichak_2.2.ts
KPSS Trend = 0.08168, Truncation lag parameter = 3, p-value = 0.1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>The Kvichak 1.3 group showed disagreement between stationairity tests indicating that a differencing is needed. The ndiff() function also disagrees but that is a reflection of the difference between the results of the adf and kpss stationairity tests. A single difference is needed to get the tests into agreement. The Kvichak 2.2 group shows an interesting disagreement between the two adf tests and ndiff() is in agreement that no differencing is needed to reach stationairity which is interesting because the adf and kpss tests were in disagreement as well. We will examine the ACF and PACF plots of both a differenced and non-differenced Kvichak 2.2 group.</p>
</section>
</section>
<section id="acf-and-pacf" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="acf-and-pacf"><span class="header-section-number">9.3</span> ACF and PACF</h2>
<section id="ugashik-1" class="level3" data-number="9.3.1">
<h3 data-number="9.3.1" class="anchored" data-anchor-id="ugashik-1"><span class="header-section-number">9.3.1</span> Ugashik</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Ugashik:</p>
<p>The PACF plot of the full differenced 1.3 age group tails off slowly, which indicates an MA() model. The ACF cuts off at 1, which further reinforces idea that this is an MA(1) model.</p>
<p>The truncated 1.3 group shows significance at a lag of 2 for both the ACF and a slow decay for the PACF. This again indicates that it will be an MA() model of MA(2)</p>
<p>The 2.2 age group has an ACF that looks like it may not have any significant lags besides the one at 5 which we are taking to indicate a cyclic nature to the data which again we will ignore in this experiment. The PACF looks to be a slow decline again. The model selection is a little more unclear in these plots.</p>
</section>
<section id="wood-1" class="level3" data-number="9.3.2">
<h3 data-number="9.3.2" class="anchored" data-anchor-id="wood-1"><span class="header-section-number">9.3.2</span> Wood</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Wood:</p>
<p>ACF for the 1.3 data seems to cut off at 2. It also shows significance at lags of 5 and 10 which may indicate seasonality. The PACF appears to slowly taper off. This is likely an MA() model</p>
<p>The 2.2 age group does not show significance in either plot, so this is most likely white noise already.</p>
</section>
<section id="kvichak-1" class="level3" data-number="9.3.3">
<h3 data-number="9.3.3" class="anchored" data-anchor-id="kvichak-1"><span class="header-section-number">9.3.3</span> Kvichak</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Kvichak:</p>
<p>The ACF and PACF for the 1.3 group both showed a barely significant lag at 1. The stationairity tests for this dataset were in disagreement so we will look to see what differencing does. After differencing the ACF cuts off at 1 and the PACF seems to slowly taper. This data may be an ARIMA(0,1,1).</p>
<p>The 2.2 group does not show any patterns that line up with an AR or MA model. It may be an ARMA model of some sort.</p>
</section>
</section>
<section id="checking-residuals" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="checking-residuals"><span class="header-section-number">9.4</span> Checking Residuals</h2>
<section id="ugashik-2" class="level3" data-number="9.4.1">
<h3 data-number="9.4.1" class="anchored" data-anchor-id="ugashik-2"><span class="header-section-number">9.4.1</span> Ugashik</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Ljung-Box test

data:  Residuals from ARIMA(0,0,1) with zero mean
Q* = 4.5946, df = 9, p-value = 0.8681

Model df: 1.   Total lags used: 10</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-19-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Ljung-Box test

data:  Residuals from ARIMA(0,0,0) with zero mean
Q* = 24.804, df = 8, p-value = 0.001678

Model df: 0.   Total lags used: 8</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-19-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Ljung-Box test

data:  Residuals from ARIMA(0,0,2) with zero mean
Q* = 12.936, df = 8, p-value = 0.1141

Model df: 2.   Total lags used: 10</code></pre>
</div>
</div>
<p>The Box tests for the residuals from the fitted models of Ugashik only reject the null hypothesis of non-autocorrelation for the truncated data. This may be a result of the cyclic nature of the salmon data. Tests for the full 1.3 and 2.2 datasets are good as they do not indicate autocorrelation in the residuals.</p>
</section>
<section id="wood-2" class="level3" data-number="9.4.2">
<h3 data-number="9.4.2" class="anchored" data-anchor-id="wood-2"><span class="header-section-number">9.4.2</span> Wood</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Ljung-Box test

data:  Residuals from ARIMA(0,1,1) with drift
Q* = 14.665, df = 9, p-value = 0.1006

Model df: 1.   Total lags used: 10</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-20-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Ljung-Box test

data:  Residuals from ARIMA(0,0,0) with non-zero mean
Q* = 9.6642, df = 10, p-value = 0.4704

Model df: 0.   Total lags used: 10</code></pre>
</div>
</div>
<p>Both fitted models for the Wood River datasets pass the residuals check. Both fail to reject the null hypothesis of non-auto correlated residuals. Indicating the residuals are white noise.</p>
</section>
<section id="kvichak-2" class="level3" data-number="9.4.3">
<h3 data-number="9.4.3" class="anchored" data-anchor-id="kvichak-2"><span class="header-section-number">9.4.3</span> Kvichak</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Ljung-Box test

data:  Residuals from ARIMA(0,1,1) with drift
Q* = 2.4224, df = 9, p-value = 0.9829

Model df: 1.   Total lags used: 10</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-21-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Ljung-Box test

data:  Residuals from ARIMA(0,0,1) with non-zero mean
Q* = 32.184, df = 9, p-value = 0.0001851

Model df: 1.   Total lags used: 10</code></pre>
</div>
</div>
<p>The fitted model for the 1.3 dataset does fail to reject the null hypothesis of non-autocorrelation indicating the residuals are white noise. In contrast, the fitted model for the 2.2 dataset does reject the null hypothesis of non-autocorrelation. This is likely another reflection of the cyclic nature of the data.</p>
</section>
</section>
<section id="fit-models-to-the-training-data" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="fit-models-to-the-training-data"><span class="header-section-number">9.5</span> Fit Models to the training data</h2>
<section id="ugashik-3" class="level3" data-number="9.5.1">
<h3 data-number="9.5.1" class="anchored" data-anchor-id="ugashik-3"><span class="header-section-number">9.5.1</span> Ugashik</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Series: train_Ugashik_1.3 
ARIMA(0,1,1) 

Coefficients:
          ma1
      -0.7305
s.e.   0.1400

sigma^2 = 18.34:  log likelihood = -134.93
AIC=273.86   AICc=274.13   BIC=277.56</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: train_Ugashik_1.3_out 
ARIMA(2,0,0) with non-zero mean 

Coefficients:
         ar1      ar2    mean
      0.3818  -0.5662  6.9256
s.e.  0.1506   0.1451  0.0890

sigma^2 = 0.365:  log likelihood = -27.2
AIC=62.41   AICc=63.94   BIC=68.14</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: train_Ugashik_2.2 
ARIMA(1,0,0) with non-zero mean 

Coefficients:
         ar1    mean
      0.4545  5.9958
s.e.  0.1268  0.3373

sigma^2 = 1.753:  log likelihood = -80.67
AIC=167.34   AICc=167.88   BIC=172.95</code></pre>
</div>
</div>
</section>
<section id="wood-3" class="level3" data-number="9.5.2">
<h3 data-number="9.5.2" class="anchored" data-anchor-id="wood-3"><span class="header-section-number">9.5.2</span> Wood</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Series: train.Wood_1.3 
ARIMA(0,1,1) 

Coefficients:
          ma1
      -0.7441
s.e.   0.0919

sigma^2 = 0.3482:  log likelihood = -41.8
AIC=87.59   AICc=87.87   BIC=91.29</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: train.Wood_2.2 
ARIMA(0,0,0) with non-zero mean 

Coefficients:
        mean
      4.6370
s.e.  0.1742

sigma^2 = 1.488:  log likelihood = -77.14
AIC=158.29   AICc=158.56   BIC=162.03</code></pre>
</div>
</div>
</section>
<section id="kvichak-3" class="level3" data-number="9.5.3">
<h3 data-number="9.5.3" class="anchored" data-anchor-id="kvichak-3"><span class="header-section-number">9.5.3</span> Kvichak</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Series: train.Kvichak_1.3 
ARIMA(0,1,1) with drift 

Coefficients:
          ma1   drift
      -0.8462  0.1083
s.e.   0.1057  0.0662

sigma^2 = 6.13:  log likelihood = -108.91
AIC=223.82   AICc=224.38   BIC=229.37</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: train.Kvichak_2.2 
ARIMA(0,0,1) with non-zero mean 

Coefficients:
         ma1    mean
      0.3950  7.4654
s.e.  0.1391  0.3395

sigma^2 = 3.002:  log likelihood = -93.56
AIC=193.11   AICc=193.66   BIC=198.73</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="results" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Results</h1>
<section id="plotting-best-fit-results-and-determining-model-accuracy" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="plotting-best-fit-results-and-determining-model-accuracy"><span class="header-section-number">10.1</span> Plotting Best Fit Results and Determining Model Accuracy</h2>
<section id="ugashik-1.3-starting-from-1980" class="level3" data-number="10.1.1">
<h3 data-number="10.1.1" class="anchored" data-anchor-id="ugashik-1.3-starting-from-1980"><span class="header-section-number">10.1.1</span> Ugashik 1.3, Starting from 1980</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-25-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-25-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Ljung-Box test

data:  Residuals from ARIMA(2,0,0) with non-zero mean
Q* = 3.6115, df = 4, p-value = 0.4611

Model df: 2.   Total lags used: 6</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                      ME      RMSE       MAE        MPE     MAPE      MASE
Training set 0.003492142 0.5741439 0.4709198 -0.6636186 6.883224 0.6078635
Test set     0.212738213 0.6585916 0.5680040  2.2757596 8.236443 0.7331798
                    ACF1 Theil's U
Training set -0.03470095        NA
Test set      0.09450154  0.877926</code></pre>
</div>
</div>
<p>The model itself seems to fit the data well based on the visual fit and the residuals.</p>
<p>The model forecast centers around the mean of the train data, predicting that 2010 will drop which fits the first few actual data points well, but doesn’t do as good of a job of predicting that the data from 2015-2020 look closer to the more recent years than further out (prior to 2005). Data are included in the confidence interval though which is great.</p>
</section>
<section id="ugashik-2.2" class="level3" data-number="10.1.2">
<h3 data-number="10.1.2" class="anchored" data-anchor-id="ugashik-2.2"><span class="header-section-number">10.1.2</span> Ugashik 2.2</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-26-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Ljung-Box test

data:  Residuals from ARIMA(1,0,0) with non-zero mean
Q* = 13.211, df = 9, p-value = 0.1533

Model df: 1.   Total lags used: 10</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                       ME     RMSE       MAE       MPE     MAPE      MASE
Training set -0.001068187 1.295973 1.0706311 -6.326379 21.04040 0.8937811
Test set     -0.314622455 1.051713 0.7971697 -9.454614 16.49798 0.6654909
                    ACF1 Theil's U
Training set -0.01828833        NA
Test set      0.31998321 0.9446332</code></pre>
</div>
</div>
<p>The model fits the timeseries train data pretty well, matching the overall change in curve. The residuals show the ACF plot has 1 significant lag reflecting the ARIMA (1,0,0) model, the histogram is fairly centered as expected, and model fails to reject Ljung-Box test.</p>
<p>Model forecast doesn’t look great. The forecast flatlines while the real data from 2011-2020 have much higher variance. This reflects the high AICc from the model. But the data are contained within the predicted confidence interval which is good. ### Wood 2.2</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-27-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Ljung-Box test

data:  Residuals from ARIMA(0,0,0) with non-zero mean
Q* = 9.263, df = 10, p-value = 0.5073

Model df: 0.   Total lags used: 10</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                       ME      RMSE       MAE         MPE     MAPE      MASE
Training set 2.309264e-14 1.2071244 0.9243868 -13.5400802 29.21208 0.6715881
Test set     8.382150e-02 0.7310041 0.6710780  -0.6671193 14.53788 0.4875535
                    ACF1 Theil's U
Training set -0.06265894        NA
Test set     -0.33015036 0.6419835</code></pre>
</div>
</div>
<p>The model fit the training data well as indicated by the Box test’s failure to reject the null hypothesis. The actual observations do fall within the 80% prediction interval This data is treated as white noise with the ARIMA(0,0,0) model so we predict the prediction intervals are tied very closely to the variance of the residuals themselves.The RMSE = 0.731</p>
</section>
<section id="wood-1.3" class="level3" data-number="10.1.3">
<h3 data-number="10.1.3" class="anchored" data-anchor-id="wood-1.3"><span class="header-section-number">10.1.3</span> Wood 1.3</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-28-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Ljung-Box test

data:  Residuals from ARIMA(0,1,1)
Q* = 12.184, df = 9, p-value = 0.2032

Model df: 1.   Total lags used: 10</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                     ME      RMSE       MAE       MPE     MAPE      MASE
Training set  0.1476159 0.5776702 0.4685250  1.486566 6.564567 0.8028471
Test set     -0.4034734 0.5321656 0.4363825 -5.476881 5.876250 0.7477688
                   ACF1 Theil's U
Training set -0.1061270        NA
Test set     -0.1945305   1.02589</code></pre>
</div>
</div>
<p>Again we see that the model fit the training dataset well. The box test fails to reject the null hypotheis. We see that the prediction intervals widen as the forecast moves forward likely due to the autocorrelation of the errors, because this is an MA(1) model, which the model has to estimate with each successive prediction. The fitted points are a flat line again because this is an MA(1) model, we would write the model as Xt = Xt-1 + error. When we fitted a model to the entire dataset, auto.arima() selected an ARIMA(0,1,1) with drift, however with just the training data auto.arima() selected an ARIMA(0,1,1) because the model does not have drift, the predictions stay as a flat line rather than having a trend.</p>
<p>the Root Mean Squared Error for this model is 0.532. This value is less than the value for the Wood_2.2 model. This is a bit surprising as they both put a straight line on the graph for predictions. These values indicate that the model for wood_1.3 was more accurate at predicting future observations. The returns of fish that spent less time in fresh water and longer in the ocean were more accurately predicted than of the fish who spent two years in both freshwater and the ocean.</p>
</section>
<section id="kvichak-2.2" class="level3" data-number="10.1.4">
<h3 data-number="10.1.4" class="anchored" data-anchor-id="kvichak-2.2"><span class="header-section-number">10.1.4</span> Kvichak 2.2</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-29-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Ljung-Box test

data:  Residuals from ARIMA(0,0,1) with non-zero mean
Q* = 36.296, df = 9, p-value = 3.513e-05

Model df: 1.   Total lags used: 10</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                       ME     RMSE      MAE        MPE     MAPE      MASE
Training set  0.008535118 1.696210 1.414096  -6.374419 21.61987 0.8022279
Test set     -0.649087674 2.088137 1.751880 -21.121893 33.24484 0.9938554
                    ACF1 Theil's U
Training set -0.02884552        NA
Test set      0.65396329   1.93424</code></pre>
</div>
</div>
<p>Here we see the cyclic nature of the data reflected in the residual’s ACF plot and the rejection of the Box test. This may have affected the model’s ability to predict. The RMSE = 2.088. The actual data points fell outside of the prediction intervals with this model. We observe the same straight line provided by the MA() model but there was more variance in this data which corresponds to the poor prediction performance ### Kvichak 1.3</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Lab-1-team-2_final_files/figure-html/unnamed-chunk-30-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Ljung-Box test

data:  Residuals from ARIMA(0,1,1) with drift
Q* = 1.9103, df = 9, p-value = 0.9928

Model df: 1.   Total lags used: 10</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                     ME     RMSE      MAE       MPE      MAPE      MASE
Training set  0.1613506 2.397324 1.399125  7.802140 22.591779 0.9296851
Test set     -0.4366868 0.650266 0.553364 -5.920379  7.288404 0.3676971
                      ACF1 Theil's U
Training set -0.0007066869        NA
Test set     -0.4030463679 0.7920795</code></pre>
</div>
</div>
<p>The model fit the training data well again based on the failure to reject the Box test and did a good job forecasting future observation. The RMSE = 0.65 for this forecast’s accuracy, we see the prediction line with a positive trend which results because the model is ARIMA(0,1,1) with drift. Due to the smaller amount of variance in this data set the points fall much closer to the straight line prediction. Again we see that returns for fish that spent longer in the ocean were more accurately predicted in this system.</p>
</section>
</section>
</section>
<section id="discussion" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Discussion</h1>
<p>We examined if fish which spent longer in the ocean were more or less predictable than fish of the same age which spent less time in the ocean. We found in the Wood and Kvichak systems that models trained on data for four year old fish which spent longer in the ocean (3 years vs 2 years) made more accurate forecasts as indicated by smaller RMSE values.</p>
<p>The predictions for the Wood and Kvichak systems were straight line predictions as the models that were selected either only had a MA component or, in the case of the Wood 2.2 age group where the observations were considered white noise already, had neither and AR or MA component. In the Ugashik system, the models fitted both had AR components and thus we see the predicted mean line has a bit of structure to it as each prediction relies on the value of the previous prediction.</p>
<p>We found that in the Ugashik system, removing the data prior to 1980 to remove increased variance in the data improved predictions from the model. This could be a good step to investigate doing for the other river systems as well which also show some unusual activity prior to 1980.</p>
</section>
<section id="description-of-each-team-members-contributions" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> Description of each team member’s contributions</h1>
<p>Dylan wrote the code for the Wood and Kvichak regions, Miranda wrote the code for the Ugashik region, and Eric and Dylan wrote sections of the report with input continued from Miranda.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../Lab-1/Final_Write_ups/Lab-1-team-1_final.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Team 1</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../Lab-1/Final_Write_ups/Lab-1-team-3_final.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Team 3</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb75" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> Team 2</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> Lab 1 Forecasting with ARIMA models</span></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Eric French (Civil), Dylan Hubl (ESRM), Miranda Mudge (Molecular &amp; Cell Bio)"</span></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a><span class="an">output:</span><span class="co"> </span></span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a><span class="co">  html_document:</span></span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a><span class="co">    code-folding: true</span></span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a><span class="co">    toc_float: true</span></span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb75-11"><a href="#cb75-11" aria-hidden="true" tabindex="-1"></a><span class="fu"># Lab 1: ARIMA models</span></span>
<span id="cb75-12"><a href="#cb75-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-13"><a href="#cb75-13" aria-hidden="true" tabindex="-1"></a>Team member names: Eric French (Civil), Dylan Hubl (ESRM), Miranda Mudge (Molecular &amp; Cell Bio)</span>
<span id="cb75-14"><a href="#cb75-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-15"><a href="#cb75-15" aria-hidden="true" tabindex="-1"></a><span class="fu"># Data</span></span>
<span id="cb75-16"><a href="#cb75-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-17"><a href="#cb75-17" aria-hidden="true" tabindex="-1"></a>We will be working with the Bristol Bay data set. Our focus will be on 4-year-old Sockeye in the Wood, Kvichak, and Ugashik regions.</span>
<span id="cb75-18"><a href="#cb75-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-21"><a href="#cb75-21" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-22"><a href="#cb75-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb75-23"><a href="#cb75-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb75-24"><a href="#cb75-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forecast)</span>
<span id="cb75-25"><a href="#cb75-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(zoo)</span>
<span id="cb75-26"><a href="#cb75-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-27"><a href="#cb75-27" aria-hidden="true" tabindex="-1"></a>bb_data <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"Lab-1"</span>, <span class="st">"Data_Images"</span>, <span class="st">"bristol_bay_data_plus_covariates.rds"</span>))</span>
<span id="cb75-28"><a href="#cb75-28" aria-hidden="true" tabindex="-1"></a>bb_data<span class="sc">$</span>log_ret <span class="ot">&lt;-</span> <span class="fu">log</span>(bb_data<span class="sc">$</span>ret)</span>
<span id="cb75-29"><a href="#cb75-29" aria-hidden="true" tabindex="-1"></a>bb_data<span class="sc">$</span>full_age <span class="ot">&lt;-</span> bb_data<span class="sc">$</span>fw_age <span class="sc">+</span> bb_data<span class="sc">$</span>o_age</span>
<span id="cb75-30"><a href="#cb75-30" aria-hidden="true" tabindex="-1"></a>rivers <span class="ot">&lt;-</span> <span class="fu">unique</span>(bb_data<span class="sc">$</span>system)</span>
<span id="cb75-31"><a href="#cb75-31" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-32"><a href="#cb75-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-33"><a href="#cb75-33" aria-hidden="true" tabindex="-1"></a><span class="fu"># Question your team will address</span></span>
<span id="cb75-34"><a href="#cb75-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-35"><a href="#cb75-35" aria-hidden="true" tabindex="-1"></a>Our group decided to compare how accurate the forecasts of best fit ARIMA models were for the populations of 4 year old salmon (1.3 and 2.2 age groups) were in the Wood, Kvichak, and Ugashik regions of the Bristol Bay data. Our questions were the following:</span>
<span id="cb75-36"><a href="#cb75-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-37"><a href="#cb75-37" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>What kind of ARIMA model best fits the population in each chosen region and age group of sockeye salmon?</span>
<span id="cb75-38"><a href="#cb75-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-39"><a href="#cb75-39" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>Which populations of salmon can be better forecast using ARIMA modeling? Those that have spent 2 years in the ocean or 3?</span>
<span id="cb75-40"><a href="#cb75-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-41"><a href="#cb75-41" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>Is there regional variation in the population changes of 4-year-old salmon?</span>
<span id="cb75-42"><a href="#cb75-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-43"><a href="#cb75-43" aria-hidden="true" tabindex="-1"></a><span class="fu"># Method you will use</span></span>
<span id="cb75-44"><a href="#cb75-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-45"><a href="#cb75-45" aria-hidden="true" tabindex="-1"></a>We will fit ARIMA models to each region and age group and compare the model structures. Then compare the forecast results of each model and comment on the accuracy of each.</span>
<span id="cb75-46"><a href="#cb75-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-47"><a href="#cb75-47" aria-hidden="true" tabindex="-1"></a><span class="fu">## Initial plan</span></span>
<span id="cb75-48"><a href="#cb75-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-49"><a href="#cb75-49" aria-hidden="true" tabindex="-1"></a>Using the forecast package, we plan to fit ARIMA models to the 1960-2010 data on 4 yr old fish in the Wood and Ugashik systems. Then forecast to 2020. We will separate the fish by time spent in freshwater and time in the ocean. These age groups are labeled 1.3 (1 year in freshwater, 3 years in the ocean) and 2.2 (2 years in freshwater, 2 years in the ocean). We will measure accuracy by the comparing the RMS error of each model.</span>
<span id="cb75-50"><a href="#cb75-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-51"><a href="#cb75-51" aria-hidden="true" tabindex="-1"></a><span class="fu">## What you actually did</span></span>
<span id="cb75-52"><a href="#cb75-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-53"><a href="#cb75-53" aria-hidden="true" tabindex="-1"></a>We were able to enact our plan with a few modifications. Instead of modeling all the 4 year old salmon together, we separated and compared them by age group from the outset. Additionally, we added the Kvichak region to our analysis. We also examined the accuracy of the forecast if we removed the years prior to 1980 from the training data for the 1.3 age group in the Ugashik river. We did this as there was increased variance in the observed data if we included 1960 - 1980. We thought that removing the variance may improve the accuracy of the forecast, so we fit a second model to the data starting at the year 1980 and compared its forecast to the original model's.</span>
<span id="cb75-54"><a href="#cb75-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-55"><a href="#cb75-55" aria-hidden="true" tabindex="-1"></a><span class="fu"># Diagnostics and preliminary exploration</span></span>
<span id="cb75-56"><a href="#cb75-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-57"><a href="#cb75-57" aria-hidden="true" tabindex="-1"></a><span class="fu">## Plot the data</span></span>
<span id="cb75-58"><a href="#cb75-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-59"><a href="#cb75-59" aria-hidden="true" tabindex="-1"></a><span class="fu">### Ugashik Region</span></span>
<span id="cb75-60"><a href="#cb75-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-63"><a href="#cb75-63" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-64"><a href="#cb75-64" aria-hidden="true" tabindex="-1"></a>age1<span class="fl">.3</span> <span class="ot">=</span> <span class="fl">1.3</span></span>
<span id="cb75-65"><a href="#cb75-65" aria-hidden="true" tabindex="-1"></a>age2<span class="fl">.2</span> <span class="ot">=</span> <span class="fl">2.2</span></span>
<span id="cb75-66"><a href="#cb75-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-67"><a href="#cb75-67" aria-hidden="true" tabindex="-1"></a><span class="co">#Create a dataframe for the 1.3 age group</span></span>
<span id="cb75-68"><a href="#cb75-68" aria-hidden="true" tabindex="-1"></a>Ugashik_1<span class="fl">.3</span> <span class="ot">&lt;-</span> bb_data <span class="sc">%&gt;%</span></span>
<span id="cb75-69"><a href="#cb75-69" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(system<span class="sc">==</span>rivers[<span class="dv">7</span>]) <span class="sc">%&gt;%</span></span>
<span id="cb75-70"><a href="#cb75-70" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(age_group <span class="sc">==</span> age1<span class="fl">.3</span>) <span class="sc">%&gt;%</span></span>
<span id="cb75-71"><a href="#cb75-71" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">year =</span> ret_yr) <span class="sc">%&gt;%</span></span>
<span id="cb75-72"><a href="#cb75-72" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(year, log_ret) </span>
<span id="cb75-73"><a href="#cb75-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-74"><a href="#cb75-74" aria-hidden="true" tabindex="-1"></a><span class="co">#Create a dataframe for the 2.2 age group</span></span>
<span id="cb75-75"><a href="#cb75-75" aria-hidden="true" tabindex="-1"></a>Ugashik_2<span class="fl">.2</span> <span class="ot">&lt;-</span> bb_data <span class="sc">%&gt;%</span></span>
<span id="cb75-76"><a href="#cb75-76" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(system<span class="sc">==</span>rivers[<span class="dv">7</span>]) <span class="sc">%&gt;%</span></span>
<span id="cb75-77"><a href="#cb75-77" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(age_group <span class="sc">==</span> age2<span class="fl">.2</span>) <span class="sc">%&gt;%</span></span>
<span id="cb75-78"><a href="#cb75-78" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">year =</span> ret_yr) <span class="sc">%&gt;%</span></span>
<span id="cb75-79"><a href="#cb75-79" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(year, log_ret)</span>
<span id="cb75-80"><a href="#cb75-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-81"><a href="#cb75-81" aria-hidden="true" tabindex="-1"></a><span class="co">#Create the time series</span></span>
<span id="cb75-82"><a href="#cb75-82" aria-hidden="true" tabindex="-1"></a>Ugashik_1.<span class="fl">3.</span>ts <span class="ot">&lt;-</span> <span class="fu">ts</span>(Ugashik_1<span class="fl">.3</span><span class="sc">$</span>log_ret, <span class="at">start=</span>Ugashik_1<span class="fl">.3</span><span class="sc">$</span>year[<span class="dv">1</span>]) <span class="co"># time series 1.3 fish </span></span>
<span id="cb75-83"><a href="#cb75-83" aria-hidden="true" tabindex="-1"></a>Ugashik_1.<span class="fl">3.</span>ts_out <span class="ot">&lt;-</span> <span class="fu">window</span>(Ugashik_1.<span class="fl">3.</span>ts, <span class="at">start=</span><span class="dv">1980</span>, <span class="at">end =</span> <span class="dv">2020</span>) <span class="co"># time series 1.3 fish starting from 1980 </span></span>
<span id="cb75-84"><a href="#cb75-84" aria-hidden="true" tabindex="-1"></a>Ugashik_2.<span class="fl">2.</span>ts <span class="ot">&lt;-</span> <span class="fu">ts</span>(Ugashik_2<span class="fl">.2</span><span class="sc">$</span>log_ret, <span class="at">start=</span>Ugashik_2<span class="fl">.2</span><span class="sc">$</span>year[<span class="dv">1</span>]) <span class="co"># time series 2.2 fish</span></span>
<span id="cb75-85"><a href="#cb75-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-86"><a href="#cb75-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-87"><a href="#cb75-87" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.ts</span>(Ugashik_1.<span class="fl">3.</span>ts, <span class="at">ylab =</span> <span class="st">"Log abundance"</span>, <span class="at">main =</span> <span class="st">"Ugashik Sockeye: 1 yr freshwater, 3 yrs ocean"</span>) </span>
<span id="cb75-88"><a href="#cb75-88" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.ts</span>(Ugashik_1.<span class="fl">3.</span>ts_out, <span class="at">ylab =</span> <span class="st">"Log abundance"</span>, <span class="at">main =</span> <span class="st">"Ugashik Sockeye: 1 yr freshwater, 3 yrs ocean</span><span class="sc">\n</span><span class="st">1980 - 2020"</span>) </span>
<span id="cb75-89"><a href="#cb75-89" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.ts</span>(Ugashik_2.<span class="fl">2.</span>ts, <span class="at">ylab =</span> <span class="st">"Log abundance"</span>, <span class="at">main =</span> <span class="st">"Ugashik Sockeye: 2 yrs freshwater, 2 yrs ocean"</span>) </span>
<span id="cb75-90"><a href="#cb75-90" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-91"><a href="#cb75-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-92"><a href="#cb75-92" aria-hidden="true" tabindex="-1"></a><span class="fu">### Wood Region</span></span>
<span id="cb75-93"><a href="#cb75-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-96"><a href="#cb75-96" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-97"><a href="#cb75-97" aria-hidden="true" tabindex="-1"></a>wood_dt <span class="ot">&lt;-</span> bb_data[(bb_data<span class="sc">$</span>system <span class="sc">==</span> rivers[<span class="dv">2</span>]) <span class="sc">&amp;</span> (bb_data<span class="sc">$</span>full_age <span class="sc">==</span> <span class="dv">4</span>),]</span>
<span id="cb75-98"><a href="#cb75-98" aria-hidden="true" tabindex="-1"></a><span class="co">#unique(wood_dt$o_age)</span></span>
<span id="cb75-99"><a href="#cb75-99" aria-hidden="true" tabindex="-1"></a><span class="co">#split the dataframe by years in the ocean</span></span>
<span id="cb75-100"><a href="#cb75-100" aria-hidden="true" tabindex="-1"></a>Wood_1<span class="fl">.3</span> <span class="ot">&lt;-</span> wood_dt[wood_dt<span class="sc">$</span>o_age<span class="sc">==</span><span class="dv">3</span>,]</span>
<span id="cb75-101"><a href="#cb75-101" aria-hidden="true" tabindex="-1"></a>Wood_2<span class="fl">.2</span> <span class="ot">&lt;-</span> wood_dt[wood_dt<span class="sc">$</span>o_age<span class="sc">==</span><span class="dv">2</span>,]</span>
<span id="cb75-102"><a href="#cb75-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-103"><a href="#cb75-103" aria-hidden="true" tabindex="-1"></a><span class="co">#make them time series</span></span>
<span id="cb75-104"><a href="#cb75-104" aria-hidden="true" tabindex="-1"></a>Wood_1.<span class="fl">3.</span>ts <span class="ot">&lt;-</span> <span class="fu">ts</span>(Wood_1<span class="fl">.3</span><span class="sc">$</span>log_ret, <span class="at">start =</span> <span class="dv">1963</span>, <span class="at">frequency =</span> <span class="dv">1</span>)</span>
<span id="cb75-105"><a href="#cb75-105" aria-hidden="true" tabindex="-1"></a>Wood_2.<span class="fl">2.</span>ts <span class="ot">&lt;-</span> <span class="fu">ts</span>(Wood_2<span class="fl">.2</span><span class="sc">$</span>log_ret, <span class="at">start =</span> <span class="dv">1963</span>, <span class="at">frequency =</span> <span class="dv">1</span>)</span>
<span id="cb75-106"><a href="#cb75-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-107"><a href="#cb75-107" aria-hidden="true" tabindex="-1"></a><span class="co">#check the plot</span></span>
<span id="cb75-108"><a href="#cb75-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-109"><a href="#cb75-109" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.ts</span>(Wood_1.<span class="fl">3.</span>ts, <span class="at">ylab =</span> <span class="st">"log Abundance"</span>, <span class="at">main =</span><span class="st">"Wood Sockeye: 1 yr freshwater, 3 yrs ocean"</span> )</span>
<span id="cb75-110"><a href="#cb75-110" aria-hidden="true" tabindex="-1"></a><span class="co">#looks like there is a positive trend to the data: not stationary, or could be stationary around a trend</span></span>
<span id="cb75-111"><a href="#cb75-111" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.ts</span>(Wood_2.<span class="fl">2.</span>ts, <span class="at">ylab =</span> <span class="st">"log Abundance"</span>, <span class="at">main =</span><span class="st">"Wood Sockeye: 2 yrs freshwater, 2 yrs ocean"</span> )</span>
<span id="cb75-112"><a href="#cb75-112" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-113"><a href="#cb75-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-114"><a href="#cb75-114" aria-hidden="true" tabindex="-1"></a><span class="fu">### Kvichak Region</span></span>
<span id="cb75-115"><a href="#cb75-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-118"><a href="#cb75-118" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-119"><a href="#cb75-119" aria-hidden="true" tabindex="-1"></a>Kvichak_dt <span class="ot">&lt;-</span> bb_data[(bb_data<span class="sc">$</span>system <span class="sc">==</span> rivers[<span class="dv">4</span>]) <span class="sc">&amp;</span> (bb_data<span class="sc">$</span>full_age <span class="sc">==</span> <span class="dv">4</span>),]</span>
<span id="cb75-120"><a href="#cb75-120" aria-hidden="true" tabindex="-1"></a><span class="co">#unique(Kvichak_dt$o_age)</span></span>
<span id="cb75-121"><a href="#cb75-121" aria-hidden="true" tabindex="-1"></a>Kvichak_1<span class="fl">.3</span> <span class="ot">&lt;-</span> Kvichak_dt[Kvichak_dt<span class="sc">$</span>o_age <span class="sc">==</span> <span class="dv">3</span>,]</span>
<span id="cb75-122"><a href="#cb75-122" aria-hidden="true" tabindex="-1"></a>Kvichak_2<span class="fl">.2</span> <span class="ot">&lt;-</span> Kvichak_dt[Kvichak_dt<span class="sc">$</span>o_age <span class="sc">==</span> <span class="dv">2</span>,]</span>
<span id="cb75-123"><a href="#cb75-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-124"><a href="#cb75-124" aria-hidden="true" tabindex="-1"></a><span class="co">#make the ts</span></span>
<span id="cb75-125"><a href="#cb75-125" aria-hidden="true" tabindex="-1"></a>Kvichak_1.<span class="fl">3.</span>ts <span class="ot">&lt;-</span> <span class="fu">ts</span>(Kvichak_1<span class="fl">.3</span><span class="sc">$</span>log_ret, <span class="at">start =</span> <span class="dv">1963</span>, <span class="at">end =</span> <span class="dv">2020</span>)</span>
<span id="cb75-126"><a href="#cb75-126" aria-hidden="true" tabindex="-1"></a>Kvichak_2.<span class="fl">2.</span>ts <span class="ot">&lt;-</span> <span class="fu">ts</span>(Kvichak_2<span class="fl">.2</span><span class="sc">$</span>log_ret, <span class="at">start =</span> <span class="dv">1963</span>, <span class="at">end =</span> <span class="dv">2020</span>)</span>
<span id="cb75-127"><a href="#cb75-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-128"><a href="#cb75-128" aria-hidden="true" tabindex="-1"></a><span class="co">#plots</span></span>
<span id="cb75-129"><a href="#cb75-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-130"><a href="#cb75-130" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Kvichak_1.<span class="fl">3.</span>ts, <span class="at">ylab =</span> <span class="st">"log Abundance"</span>, <span class="at">main =</span> <span class="st">"Kvichak Sockeye: 1 yr freshwater, 3 yrs ocean"</span> )</span>
<span id="cb75-131"><a href="#cb75-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-132"><a href="#cb75-132" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Kvichak_2.<span class="fl">2.</span>ts, <span class="at">ylab =</span> <span class="st">"log Abundance"</span>, <span class="at">main =</span> <span class="st">"Kvichak Sockeye: 2 yrsfreshwater, 2 yrs ocean"</span> )</span>
<span id="cb75-133"><a href="#cb75-133" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-134"><a href="#cb75-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-135"><a href="#cb75-135" aria-hidden="true" tabindex="-1"></a>Uvashik: Upon observing the 1.3 time series, there is a clear outlier value at 1977. To remove the negative value, we re-plotted the data starting at 1980 instead of 1967. The new time series seems to show variance around a mean of 7. The 2.2 group appears to show variance around a mean of 5. Differencing the data will likely show stationarity</span>
<span id="cb75-136"><a href="#cb75-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-137"><a href="#cb75-137" aria-hidden="true" tabindex="-1"></a>Wood: The 1.3 age group appears to have a positive trend, so it is likely not stationary. It could be stationary around a trend. The 2.2 age group does not seem to have any trends, and could be stationary around a mean of 4.</span>
<span id="cb75-138"><a href="#cb75-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-139"><a href="#cb75-139" aria-hidden="true" tabindex="-1"></a>Kvichak: There is another negative outlier in the 1.3 age group, otherwise the data appears to be stationary around a mean of 7. We will have to see how much influence the outlier has on the ARIMA model. The 2.2 age group does not show any obvious trends and seems to be stationary around a mean of 7.</span>
<span id="cb75-140"><a href="#cb75-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-141"><a href="#cb75-141" aria-hidden="true" tabindex="-1"></a><span class="fu">## Testing for Stationarity</span></span>
<span id="cb75-142"><a href="#cb75-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-143"><a href="#cb75-143" aria-hidden="true" tabindex="-1"></a><span class="fu">### Ugashik</span></span>
<span id="cb75-144"><a href="#cb75-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-147"><a href="#cb75-147" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-148"><a href="#cb75-148" aria-hidden="true" tabindex="-1"></a><span class="co">#Miranda's Code</span></span>
<span id="cb75-149"><a href="#cb75-149" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">adf.test</span>(Ugashik_1.<span class="fl">3.</span>ts) </span>
<span id="cb75-150"><a href="#cb75-150" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">kpss.test</span>(Ugashik_1.<span class="fl">3.</span>ts, <span class="at">null =</span> <span class="st">"Level"</span>) </span>
<span id="cb75-151"><a href="#cb75-151" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">kpss.test</span>(Ugashik_1.<span class="fl">3.</span>ts, <span class="at">null =</span> <span class="st">"Trend"</span>) </span>
<span id="cb75-152"><a href="#cb75-152" aria-hidden="true" tabindex="-1"></a>datts_diff_1<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">diff</span>(Ugashik_1.<span class="fl">3.</span>ts, <span class="at">differences =</span> <span class="dv">1</span>)</span>
<span id="cb75-153"><a href="#cb75-153" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">adf.test</span>(Ugashik_1.<span class="fl">3.</span>ts_out) </span>
<span id="cb75-154"><a href="#cb75-154" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">kpss.test</span>(Ugashik_1.<span class="fl">3.</span>ts_out, <span class="at">null =</span> <span class="st">"Level"</span>) </span>
<span id="cb75-155"><a href="#cb75-155" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">kpss.test</span>(Ugashik_1.<span class="fl">3.</span>ts_out, <span class="at">null =</span> <span class="st">"Trend"</span>) </span>
<span id="cb75-156"><a href="#cb75-156" aria-hidden="true" tabindex="-1"></a>datts_diff_1<span class="fl">.3</span>_out <span class="ot">&lt;-</span> <span class="fu">diff</span>(Ugashik_1.<span class="fl">3.</span>ts_out, <span class="at">differences =</span> <span class="dv">1</span>)</span>
<span id="cb75-157"><a href="#cb75-157" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(datts_diff_1<span class="fl">.3</span>, <span class="at">ylab =</span> <span class="st">"Log abundance"</span>, <span class="at">main =</span> <span class="st">"Time series, first differenced:</span><span class="sc">\n</span><span class="st"> 1 year freshwater, 3 years ocean"</span>)</span>
<span id="cb75-158"><a href="#cb75-158" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(datts_diff_1<span class="fl">.3</span>_out, <span class="at">ylab =</span> <span class="st">"Log abundance"</span>, <span class="at">main =</span> <span class="st">"Time series, first differenced:</span><span class="sc">\n</span><span class="st"> 1 year freshwater, 3 years ocean, outlier removed"</span>)</span>
<span id="cb75-159"><a href="#cb75-159" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-160"><a href="#cb75-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-163"><a href="#cb75-163" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-164"><a href="#cb75-164" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">adf.test</span>(Ugashik_2.<span class="fl">2.</span>ts) </span>
<span id="cb75-165"><a href="#cb75-165" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">kpss.test</span>(Ugashik_2.<span class="fl">2.</span>ts, <span class="at">null =</span> <span class="st">"Level"</span>) </span>
<span id="cb75-166"><a href="#cb75-166" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">kpss.test</span>(Ugashik_2.<span class="fl">2.</span>ts, <span class="at">null =</span> <span class="st">"Trend"</span>)</span>
<span id="cb75-167"><a href="#cb75-167" aria-hidden="true" tabindex="-1"></a>datts_diff_2<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">diff</span>(Ugashik_2.<span class="fl">2.</span>ts, <span class="at">differences =</span> <span class="dv">1</span>)</span>
<span id="cb75-168"><a href="#cb75-168" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(datts_diff_2<span class="fl">.2</span>, <span class="at">ylab =</span> <span class="st">"Log abundance"</span>, <span class="at">main =</span> <span class="st">"Time series, first differenced:</span><span class="sc">\n</span><span class="st"> 2 years freshwater, 2 years ocean"</span>)</span>
<span id="cb75-169"><a href="#cb75-169" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-170"><a href="#cb75-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-171"><a href="#cb75-171" aria-hidden="true" tabindex="-1"></a>Stationairity test for the full Ugashik 1.3 group were in disagreement indicating that a single difference should be taken to get them to agree on stationairity. The same is true for the 2.2 group, we again see disagreement in the tests. The truncated dataset of the 1.3 group shows full agreement on non-stationairity. Thus a first difference needs to be taken on all of them. </span>
<span id="cb75-172"><a href="#cb75-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-173"><a href="#cb75-173" aria-hidden="true" tabindex="-1"></a><span class="fu">### Wood</span></span>
<span id="cb75-176"><a href="#cb75-176" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-177"><a href="#cb75-177" aria-hidden="true" tabindex="-1"></a><span class="co">#Dylan's Code</span></span>
<span id="cb75-178"><a href="#cb75-178" aria-hidden="true" tabindex="-1"></a><span class="co">#Wood_1.3.ts testing</span></span>
<span id="cb75-179"><a href="#cb75-179" aria-hidden="true" tabindex="-1"></a><span class="co">#run tests for stationarity</span></span>
<span id="cb75-180"><a href="#cb75-180" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">adf.test</span>(Wood_1.<span class="fl">3.</span>ts)                  <span class="co"># fails to reject: Non-stationary</span></span>
<span id="cb75-181"><a href="#cb75-181" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">adf.test</span>(Wood_1.<span class="fl">3.</span>ts,<span class="at">k =</span> <span class="dv">0</span>)            <span class="co">#forced it to test AR(1) it does reject: Stationary. So conflicts with the test above</span></span>
<span id="cb75-182"><a href="#cb75-182" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">kpss.test</span>(Wood_1.<span class="fl">3.</span>ts, <span class="at">null =</span> <span class="st">"Level"</span>) <span class="co">#not sure this test makes sense, visually there is a trend in the data. opposite null hypothesis for kpss it rejects: Non-stationary</span></span>
<span id="cb75-183"><a href="#cb75-183" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">kpss.test</span>(Wood_1.<span class="fl">3.</span>ts, <span class="at">null =</span> <span class="st">"Trend"</span>) <span class="co">#this tested to see if data is stationary around a trend</span></span>
<span id="cb75-184"><a href="#cb75-184" aria-hidden="true" tabindex="-1"></a>forecast<span class="sc">::</span><span class="fu">ndiffs</span>(Wood_1.<span class="fl">3.</span>ts, <span class="at">test =</span> <span class="st">"kpss"</span>)    <span class="co"># 1 difference needed</span></span>
<span id="cb75-185"><a href="#cb75-185" aria-hidden="true" tabindex="-1"></a>forecast<span class="sc">::</span><span class="fu">ndiffs</span>(Wood_1.<span class="fl">3.</span>ts, <span class="at">test =</span> <span class="st">"adf"</span>)     <span class="co"># 0 differences needed, again disagreement. Likely will need a difference but we can compare to the ARIMA model that gets automatically fit</span></span>
<span id="cb75-186"><a href="#cb75-186" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-187"><a href="#cb75-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-190"><a href="#cb75-190" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-191"><a href="#cb75-191" aria-hidden="true" tabindex="-1"></a><span class="co">#Wood_2.2.ts testing</span></span>
<span id="cb75-192"><a href="#cb75-192" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">adf.test</span>(Wood_2.<span class="fl">2.</span>ts)                  <span class="co"># Rejects: stationary</span></span>
<span id="cb75-193"><a href="#cb75-193" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">adf.test</span>(Wood_2.<span class="fl">2.</span>ts,<span class="at">k =</span> <span class="dv">0</span>)            <span class="co">#forced it to test AR(1) it does reject: Stationary</span></span>
<span id="cb75-194"><a href="#cb75-194" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">kpss.test</span>(Wood_2.<span class="fl">2.</span>ts, <span class="at">null =</span> <span class="st">"Level"</span>) <span class="co">#opposite null hypothesis for kpss it fails to reject: Stationary</span></span>
<span id="cb75-195"><a href="#cb75-195" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">kpss.test</span>(Wood_2.<span class="fl">2.</span>ts, <span class="at">null =</span> <span class="st">"Trend"</span>) </span>
<span id="cb75-196"><a href="#cb75-196" aria-hidden="true" tabindex="-1"></a>forecast<span class="sc">::</span><span class="fu">ndiffs</span>(Wood_2.<span class="fl">2.</span>ts, <span class="at">test =</span> <span class="st">"kpss"</span>)    <span class="co"># 0 needed</span></span>
<span id="cb75-197"><a href="#cb75-197" aria-hidden="true" tabindex="-1"></a>forecast<span class="sc">::</span><span class="fu">ndiffs</span>(Wood_2.<span class="fl">2.</span>ts, <span class="at">test =</span> <span class="st">"adf"</span>)     <span class="co"># 0 needed. Agrees with the unit root tests above that found stationairity of the data</span></span>
<span id="cb75-198"><a href="#cb75-198" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-199"><a href="#cb75-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-200"><a href="#cb75-200" aria-hidden="true" tabindex="-1"></a>The Wood River 1.3 showed disagreement in the outcome of the stationairity tests this indicates that a difference is required to reach stationairity. The ndiff() function disagrees based on test used but the kpss test indicates a single differencing is required. In contrast the Wood River 2.2 group has full agreement from all tests for stationairity. The ndiff() function also indicates that no differencing is required for this dataset. </span>
<span id="cb75-201"><a href="#cb75-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-202"><a href="#cb75-202" aria-hidden="true" tabindex="-1"></a><span class="fu">### Kvichak</span></span>
<span id="cb75-205"><a href="#cb75-205" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-206"><a href="#cb75-206" aria-hidden="true" tabindex="-1"></a><span class="co">#test stationairity Kvichak_1.3</span></span>
<span id="cb75-207"><a href="#cb75-207" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">adf.test</span>(Kvichak_1.<span class="fl">3.</span>ts)                  <span class="co">#  Rejects just barely: stationary</span></span>
<span id="cb75-208"><a href="#cb75-208" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">adf.test</span>(Kvichak_1.<span class="fl">3.</span>ts,<span class="at">k =</span> <span class="dv">0</span>)            <span class="co">#forced it to test AR(1) it does reject: Stationary.</span></span>
<span id="cb75-209"><a href="#cb75-209" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">kpss.test</span>(Kvichak_1.<span class="fl">3.</span>ts, <span class="at">null =</span> <span class="st">"Level"</span>) <span class="co">#opposite null hypothesis for kpss it  rejects: non-Stationary</span></span>
<span id="cb75-210"><a href="#cb75-210" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">kpss.test</span>(Kvichak_1.<span class="fl">3.</span>ts, <span class="at">null =</span> <span class="st">"Trend"</span>) <span class="co">#.it rejects:non- stationary</span></span>
<span id="cb75-211"><a href="#cb75-211" aria-hidden="true" tabindex="-1"></a>forecast<span class="sc">::</span><span class="fu">ndiffs</span>(Kvichak_1.<span class="fl">3.</span>ts, <span class="at">test =</span> <span class="st">"kpss"</span>)    <span class="co"># 1 needed</span></span>
<span id="cb75-212"><a href="#cb75-212" aria-hidden="true" tabindex="-1"></a>forecast<span class="sc">::</span><span class="fu">ndiffs</span>(Kvichak_1.<span class="fl">3.</span>ts, <span class="at">test =</span> <span class="st">"adf"</span>)     <span class="co">#0 needed. again disagreement. likely will be differenced by auto.arima()</span></span>
<span id="cb75-213"><a href="#cb75-213" aria-hidden="true" tabindex="-1"></a><span class="co">#there is disagreement from adf and kpss, may require differencing</span></span>
<span id="cb75-214"><a href="#cb75-214" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-215"><a href="#cb75-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-218"><a href="#cb75-218" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-219"><a href="#cb75-219" aria-hidden="true" tabindex="-1"></a><span class="co">#test stationairity Kvichak_2.2</span></span>
<span id="cb75-220"><a href="#cb75-220" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">adf.test</span>(Kvichak_2.<span class="fl">2.</span>ts) <span class="co"># fails to Reject: non-stationary</span></span>
<span id="cb75-221"><a href="#cb75-221" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">adf.test</span>(Kvichak_2.<span class="fl">2.</span>ts,<span class="at">k =</span> <span class="dv">0</span>)            <span class="co">#forced it to test AR(1) it does reject: Stationary. disagreement between them</span></span>
<span id="cb75-222"><a href="#cb75-222" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">kpss.test</span>(Kvichak_2.<span class="fl">2.</span>ts, <span class="at">null =</span> <span class="st">"Level"</span>) <span class="co">#opposite null hypothesis for kpss it fails to reject: Stationary</span></span>
<span id="cb75-223"><a href="#cb75-223" aria-hidden="true" tabindex="-1"></a>tseries<span class="sc">::</span><span class="fu">kpss.test</span>(Kvichak_2.<span class="fl">2.</span>ts, <span class="at">null =</span> <span class="st">"Trend"</span>)</span>
<span id="cb75-224"><a href="#cb75-224" aria-hidden="true" tabindex="-1"></a><span class="co">#there is disagreement from adf and kpss, may require differencing</span></span>
<span id="cb75-225"><a href="#cb75-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-226"><a href="#cb75-226" aria-hidden="true" tabindex="-1"></a>forecast<span class="sc">::</span><span class="fu">ndiffs</span>(Kvichak_2.<span class="fl">2.</span>ts, <span class="at">test =</span> <span class="st">"kpss"</span>)    <span class="co"># 0 needed</span></span>
<span id="cb75-227"><a href="#cb75-227" aria-hidden="true" tabindex="-1"></a>forecast<span class="sc">::</span><span class="fu">ndiffs</span>(Kvichak_2.<span class="fl">2.</span>ts, <span class="at">test =</span> <span class="st">"adf"</span>)     <span class="co"># 0 needed. So I am expecting this to be an AR(1) as the full adf test was the only one to say non-stationary</span></span>
<span id="cb75-228"><a href="#cb75-228" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-229"><a href="#cb75-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-230"><a href="#cb75-230" aria-hidden="true" tabindex="-1"></a>The Kvichak 1.3 group showed disagreement between stationairity tests indicating that a differencing is needed. The ndiff() function also disagrees but that is a reflection of the difference between the results of the adf and kpss stationairity tests. A single difference is needed to get the tests into agreement. The Kvichak 2.2 group shows an interesting disagreement between the two adf tests and ndiff() is in agreement that no differencing is needed to reach stationairity which is interesting because the adf and kpss tests were in disagreement as well. We will examine the ACF and PACF plots of both a differenced and non-differenced Kvichak 2.2 group.</span>
<span id="cb75-231"><a href="#cb75-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-232"><a href="#cb75-232" aria-hidden="true" tabindex="-1"></a><span class="fu">## ACF and PACF</span></span>
<span id="cb75-233"><a href="#cb75-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-234"><a href="#cb75-234" aria-hidden="true" tabindex="-1"></a><span class="fu">### Ugashik</span></span>
<span id="cb75-235"><a href="#cb75-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-238"><a href="#cb75-238" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-239"><a href="#cb75-239" aria-hidden="true" tabindex="-1"></a>layout_matrix_1 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>),<span class="at">ncol=</span><span class="dv">2</span>)  <span class="co">#setting up how the plots will display</span></span>
<span id="cb75-240"><a href="#cb75-240" aria-hidden="true" tabindex="-1"></a><span class="fu">layout</span>(layout_matrix_1)                   </span>
<span id="cb75-241"><a href="#cb75-241" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(<span class="fu">diff</span>(Ugashik_1.<span class="fl">3.</span>ts))</span>
<span id="cb75-242"><a href="#cb75-242" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(<span class="fu">diff</span>(Ugashik_1.<span class="fl">3.</span>ts))</span>
<span id="cb75-243"><a href="#cb75-243" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-244"><a href="#cb75-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-247"><a href="#cb75-247" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-248"><a href="#cb75-248" aria-hidden="true" tabindex="-1"></a><span class="fu">layout</span>(layout_matrix_1)                   <span class="co">#setting up how the plots will display</span></span>
<span id="cb75-249"><a href="#cb75-249" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(<span class="fu">diff</span>(Ugashik_1.<span class="fl">3.</span>ts_out), <span class="at">na.action =</span> na.pass) <span class="co"># allows na value</span></span>
<span id="cb75-250"><a href="#cb75-250" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(<span class="fu">diff</span>(Ugashik_1.<span class="fl">3.</span>ts_out),<span class="at">na.action =</span> na.pass)</span>
<span id="cb75-251"><a href="#cb75-251" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-252"><a href="#cb75-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-255"><a href="#cb75-255" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-256"><a href="#cb75-256" aria-hidden="true" tabindex="-1"></a><span class="fu">layout</span>(layout_matrix_1)                   <span class="co">#setting up how the plots will display</span></span>
<span id="cb75-257"><a href="#cb75-257" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(<span class="fu">diff</span>(Ugashik_2.<span class="fl">2.</span>ts))</span>
<span id="cb75-258"><a href="#cb75-258" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(<span class="fu">diff</span>(Ugashik_2.<span class="fl">2.</span>ts))</span>
<span id="cb75-259"><a href="#cb75-259" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-260"><a href="#cb75-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-261"><a href="#cb75-261" aria-hidden="true" tabindex="-1"></a>Ugashik:</span>
<span id="cb75-262"><a href="#cb75-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-263"><a href="#cb75-263" aria-hidden="true" tabindex="-1"></a>The PACF plot of the full differenced 1.3 age group tails off slowly, which indicates an MA() model. The ACF cuts off at 1, which further reinforces idea that this is an MA(1) model.</span>
<span id="cb75-264"><a href="#cb75-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-265"><a href="#cb75-265" aria-hidden="true" tabindex="-1"></a>The truncated 1.3 group shows significance at a lag of 2 for both the ACF and a slow decay for the PACF. This again indicates that it will be an MA() model of MA(2)</span>
<span id="cb75-266"><a href="#cb75-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-267"><a href="#cb75-267" aria-hidden="true" tabindex="-1"></a>The 2.2 age group has an ACF that looks like it may not have any significant lags besides the one at 5 which we are taking to indicate a cyclic nature to the data which again we will ignore in this experiment. The PACF looks to be a slow decline again. The model selection is a little more unclear in these plots.</span>
<span id="cb75-268"><a href="#cb75-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-269"><a href="#cb75-269" aria-hidden="true" tabindex="-1"></a><span class="fu">### Wood</span></span>
<span id="cb75-270"><a href="#cb75-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-273"><a href="#cb75-273" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-274"><a href="#cb75-274" aria-hidden="true" tabindex="-1"></a><span class="co">#acf and pacf for differenced Wood_1.3</span></span>
<span id="cb75-275"><a href="#cb75-275" aria-hidden="true" tabindex="-1"></a><span class="fu">layout</span>(layout_matrix_1)                   <span class="co">#setting up how the plots will display</span></span>
<span id="cb75-276"><a href="#cb75-276" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(<span class="fu">diff</span>(Wood_1.<span class="fl">3.</span>ts))</span>
<span id="cb75-277"><a href="#cb75-277" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(<span class="fu">diff</span>(Wood_1.<span class="fl">3.</span>ts))</span>
<span id="cb75-278"><a href="#cb75-278" aria-hidden="true" tabindex="-1"></a><span class="co">#pacf looks like a slow decay indicating it will be and MA model. signif lags at 1, 5, 10 on ACF</span></span>
<span id="cb75-279"><a href="#cb75-279" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-280"><a href="#cb75-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-283"><a href="#cb75-283" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-284"><a href="#cb75-284" aria-hidden="true" tabindex="-1"></a><span class="co">#acf and pacf for Wood_2.2</span></span>
<span id="cb75-285"><a href="#cb75-285" aria-hidden="true" tabindex="-1"></a><span class="co">#carries the plot display set up from the above over to these plots</span></span>
<span id="cb75-286"><a href="#cb75-286" aria-hidden="true" tabindex="-1"></a><span class="fu">layout</span>(layout_matrix_1)                   <span class="co">#setting up how the plots will display</span></span>
<span id="cb75-287"><a href="#cb75-287" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(Wood_2.<span class="fl">2.</span>ts)</span>
<span id="cb75-288"><a href="#cb75-288" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(Wood_2.<span class="fl">2.</span>ts)</span>
<span id="cb75-289"><a href="#cb75-289" aria-hidden="true" tabindex="-1"></a><span class="co">#no significant lags in either plot. This is white noise, no autocorrelation. expecting ARIMA(0,0,0)</span></span>
<span id="cb75-290"><a href="#cb75-290" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-291"><a href="#cb75-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-292"><a href="#cb75-292" aria-hidden="true" tabindex="-1"></a>Wood:</span>
<span id="cb75-293"><a href="#cb75-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-294"><a href="#cb75-294" aria-hidden="true" tabindex="-1"></a>ACF for the 1.3 data seems to cut off at 2. It also shows significance at lags of 5 and 10 which may indicate seasonality. The PACF appears to slowly taper off. This is likely an MA() model</span>
<span id="cb75-295"><a href="#cb75-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-296"><a href="#cb75-296" aria-hidden="true" tabindex="-1"></a>The 2.2 age group does not show significance in either plot, so this is most likely white noise already.</span>
<span id="cb75-297"><a href="#cb75-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-298"><a href="#cb75-298" aria-hidden="true" tabindex="-1"></a><span class="fu">### Kvichak</span></span>
<span id="cb75-299"><a href="#cb75-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-302"><a href="#cb75-302" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-303"><a href="#cb75-303" aria-hidden="true" tabindex="-1"></a><span class="fu">layout</span>(layout_matrix_1)                   <span class="co">#setting up how the plots will display</span></span>
<span id="cb75-304"><a href="#cb75-304" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(Kvichak_1.<span class="fl">3.</span>ts)</span>
<span id="cb75-305"><a href="#cb75-305" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(Kvichak_1.<span class="fl">3.</span>ts)</span>
<span id="cb75-306"><a href="#cb75-306" aria-hidden="true" tabindex="-1"></a><span class="co">#both have a significant lag at 1. maybe just a differencing will help</span></span>
<span id="cb75-307"><a href="#cb75-307" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-308"><a href="#cb75-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-311"><a href="#cb75-311" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-312"><a href="#cb75-312" aria-hidden="true" tabindex="-1"></a><span class="fu">layout</span>(layout_matrix_1)                   <span class="co">#setting up how the plots will display</span></span>
<span id="cb75-313"><a href="#cb75-313" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(<span class="fu">diff</span>(Kvichak_1.<span class="fl">3.</span>ts))</span>
<span id="cb75-314"><a href="#cb75-314" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(<span class="fu">diff</span>(Kvichak_1.<span class="fl">3.</span>ts))</span>
<span id="cb75-315"><a href="#cb75-315" aria-hidden="true" tabindex="-1"></a><span class="co">#looks like slow decay on pacf and a significant lag at 1 on acf. expecting an ARIMA(0,1,1)</span></span>
<span id="cb75-316"><a href="#cb75-316" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-317"><a href="#cb75-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-320"><a href="#cb75-320" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-321"><a href="#cb75-321" aria-hidden="true" tabindex="-1"></a><span class="co">#plot acf and pacf</span></span>
<span id="cb75-322"><a href="#cb75-322" aria-hidden="true" tabindex="-1"></a><span class="fu">layout</span>(layout_matrix_1)</span>
<span id="cb75-323"><a href="#cb75-323" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(Kvichak_2.<span class="fl">2.</span>ts)</span>
<span id="cb75-324"><a href="#cb75-324" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(Kvichak_2.<span class="fl">2.</span>ts)</span>
<span id="cb75-325"><a href="#cb75-325" aria-hidden="true" tabindex="-1"></a><span class="co">#neither shows any clear lag or decay signs. maybe an combined ARMA model</span></span>
<span id="cb75-326"><a href="#cb75-326" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-327"><a href="#cb75-327" aria-hidden="true" tabindex="-1"></a>Kvichak:</span>
<span id="cb75-328"><a href="#cb75-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-329"><a href="#cb75-329" aria-hidden="true" tabindex="-1"></a>The ACF and PACF for the 1.3 group both showed a barely significant lag at 1. The stationairity tests for this dataset were in disagreement so we will look to see what differencing does. After differencing the ACF cuts off at 1 and the PACF seems to slowly taper. This data may be an ARIMA(0,1,1).</span>
<span id="cb75-330"><a href="#cb75-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-331"><a href="#cb75-331" aria-hidden="true" tabindex="-1"></a>The 2.2 group does not show any patterns that line up with an AR or MA model. It may be an ARMA model of some sort.</span>
<span id="cb75-332"><a href="#cb75-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-333"><a href="#cb75-333" aria-hidden="true" tabindex="-1"></a><span class="fu">## Checking Residuals</span></span>
<span id="cb75-334"><a href="#cb75-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-335"><a href="#cb75-335" aria-hidden="true" tabindex="-1"></a><span class="fu">### Ugashik</span></span>
<span id="cb75-336"><a href="#cb75-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-339"><a href="#cb75-339" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-340"><a href="#cb75-340" aria-hidden="true" tabindex="-1"></a>fit.ugashik_1<span class="fl">.3</span> <span class="ot">&lt;-</span> forecast<span class="sc">::</span><span class="fu">auto.arima</span>(<span class="fu">diff</span>(Ugashik_1.<span class="fl">3.</span>ts))</span>
<span id="cb75-341"><a href="#cb75-341" aria-hidden="true" tabindex="-1"></a>fit.ugashik_1<span class="fl">.3</span>_out <span class="ot">&lt;-</span> forecast<span class="sc">::</span><span class="fu">auto.arima</span>(<span class="fu">diff</span>(Ugashik_1.<span class="fl">3.</span>ts_out))</span>
<span id="cb75-342"><a href="#cb75-342" aria-hidden="true" tabindex="-1"></a>fit.ugashik_2<span class="fl">.2</span> <span class="ot">&lt;-</span> forecast<span class="sc">::</span><span class="fu">auto.arima</span>(<span class="fu">diff</span>(Ugashik_2.<span class="fl">2.</span>ts))</span>
<span id="cb75-343"><a href="#cb75-343" aria-hidden="true" tabindex="-1"></a>forecast<span class="sc">::</span><span class="fu">checkresiduals</span>(fit.ugashik_1<span class="fl">.3</span>)   </span>
<span id="cb75-344"><a href="#cb75-344" aria-hidden="true" tabindex="-1"></a>forecast<span class="sc">::</span><span class="fu">checkresiduals</span>(fit.ugashik_1<span class="fl">.3</span>_out)</span>
<span id="cb75-345"><a href="#cb75-345" aria-hidden="true" tabindex="-1"></a>forecast<span class="sc">::</span><span class="fu">checkresiduals</span>(fit.ugashik_2<span class="fl">.2</span>)</span>
<span id="cb75-346"><a href="#cb75-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-347"><a href="#cb75-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-348"><a href="#cb75-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-349"><a href="#cb75-349" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-350"><a href="#cb75-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-351"><a href="#cb75-351" aria-hidden="true" tabindex="-1"></a>The Box tests for the residuals from the fitted models of Ugashik only reject the null hypothesis of non-autocorrelation for the truncated data. This may be a result of the cyclic nature of the salmon data. Tests for the full 1.3 and 2.2 datasets are good as they do not indicate autocorrelation in the residuals.</span>
<span id="cb75-352"><a href="#cb75-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-353"><a href="#cb75-353" aria-hidden="true" tabindex="-1"></a><span class="fu">### Wood</span></span>
<span id="cb75-354"><a href="#cb75-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-357"><a href="#cb75-357" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-358"><a href="#cb75-358" aria-hidden="true" tabindex="-1"></a>fit.wood_1<span class="fl">.3</span> <span class="ot">&lt;-</span> forecast<span class="sc">::</span><span class="fu">auto.arima</span>(Wood_1.<span class="fl">3.</span>ts)</span>
<span id="cb75-359"><a href="#cb75-359" aria-hidden="true" tabindex="-1"></a>fit.wood_2<span class="fl">.2</span> <span class="ot">&lt;-</span> forecast<span class="sc">::</span><span class="fu">auto.arima</span>(Wood_2.<span class="fl">2.</span>ts)</span>
<span id="cb75-360"><a href="#cb75-360" aria-hidden="true" tabindex="-1"></a>forecast<span class="sc">::</span><span class="fu">checkresiduals</span>(fit.wood_1<span class="fl">.3</span>)</span>
<span id="cb75-361"><a href="#cb75-361" aria-hidden="true" tabindex="-1"></a>forecast<span class="sc">::</span><span class="fu">checkresiduals</span>(fit.wood_2<span class="fl">.2</span>)</span>
<span id="cb75-362"><a href="#cb75-362" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-363"><a href="#cb75-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-364"><a href="#cb75-364" aria-hidden="true" tabindex="-1"></a>Both fitted models for the Wood River datasets pass the residuals check. Both fail to reject the null hypothesis of non-auto correlated residuals. Indicating the residuals are white noise.</span>
<span id="cb75-365"><a href="#cb75-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-366"><a href="#cb75-366" aria-hidden="true" tabindex="-1"></a><span class="fu">### Kvichak</span></span>
<span id="cb75-367"><a href="#cb75-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-370"><a href="#cb75-370" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-371"><a href="#cb75-371" aria-hidden="true" tabindex="-1"></a>fit.kvi<span class="fl">.3</span> <span class="ot">&lt;-</span> forecast<span class="sc">::</span><span class="fu">auto.arima</span>(Kvichak_1.<span class="fl">3.</span>ts)</span>
<span id="cb75-372"><a href="#cb75-372" aria-hidden="true" tabindex="-1"></a>fit.kvi<span class="fl">.2</span> <span class="ot">&lt;-</span> forecast<span class="sc">::</span><span class="fu">auto.arima</span>(Kvichak_2.<span class="fl">2.</span>ts)</span>
<span id="cb75-373"><a href="#cb75-373" aria-hidden="true" tabindex="-1"></a>forecast<span class="sc">::</span><span class="fu">checkresiduals</span>(fit.kvi<span class="fl">.3</span>)</span>
<span id="cb75-374"><a href="#cb75-374" aria-hidden="true" tabindex="-1"></a>forecast<span class="sc">::</span><span class="fu">checkresiduals</span>(fit.kvi<span class="fl">.2</span>)</span>
<span id="cb75-375"><a href="#cb75-375" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-376"><a href="#cb75-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-377"><a href="#cb75-377" aria-hidden="true" tabindex="-1"></a>The fitted model for the 1.3 dataset does fail to reject the null hypothesis of non-autocorrelation indicating the residuals are white noise. In contrast, the fitted model for the 2.2 dataset does reject the null hypothesis of non-autocorrelation. This is likely another reflection of the cyclic nature of the data.</span>
<span id="cb75-378"><a href="#cb75-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-379"><a href="#cb75-379" aria-hidden="true" tabindex="-1"></a><span class="fu">## Fit Models to the training data</span></span>
<span id="cb75-380"><a href="#cb75-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-381"><a href="#cb75-381" aria-hidden="true" tabindex="-1"></a><span class="fu">### Ugashik</span></span>
<span id="cb75-382"><a href="#cb75-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-385"><a href="#cb75-385" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-386"><a href="#cb75-386" aria-hidden="true" tabindex="-1"></a><span class="co"># Make dataframes for testing models later</span></span>
<span id="cb75-387"><a href="#cb75-387" aria-hidden="true" tabindex="-1"></a>train_Ugashik_1<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">window</span>(Ugashik_1.<span class="fl">3.</span>ts, <span class="dv">1963</span>, <span class="dv">2010</span>) <span class="co"># range 1963 - 2010</span></span>
<span id="cb75-388"><a href="#cb75-388" aria-hidden="true" tabindex="-1"></a>test_Ugashik_1<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">window</span>(Ugashik_1.<span class="fl">3.</span>ts, <span class="dv">2011</span>, <span class="dv">2020</span>) <span class="co"># range 2011 - 2020</span></span>
<span id="cb75-389"><a href="#cb75-389" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-390"><a href="#cb75-390" aria-hidden="true" tabindex="-1"></a>train_Ugashik_1<span class="fl">.3</span>_out <span class="ot">&lt;-</span> <span class="fu">window</span>(Ugashik_1.<span class="fl">3.</span>ts_out, <span class="dv">1980</span>, <span class="dv">2010</span>) <span class="co"># range 1963 - 2010</span></span>
<span id="cb75-391"><a href="#cb75-391" aria-hidden="true" tabindex="-1"></a>test_Ugashik_1<span class="fl">.3</span>_out <span class="ot">&lt;-</span> <span class="fu">window</span>(Ugashik_1.<span class="fl">3.</span>ts_out, <span class="dv">2011</span>, <span class="dv">2020</span>) <span class="co"># range 2011 - 2020</span></span>
<span id="cb75-392"><a href="#cb75-392" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-393"><a href="#cb75-393" aria-hidden="true" tabindex="-1"></a>train_Ugashik_2<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">window</span>(Ugashik_2.<span class="fl">2.</span>ts, <span class="dv">1963</span>, <span class="dv">2010</span>) <span class="co"># range 1963 - 2010</span></span>
<span id="cb75-394"><a href="#cb75-394" aria-hidden="true" tabindex="-1"></a>test_Ugashik_2<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">window</span>(Ugashik_2.<span class="fl">2.</span>ts, <span class="dv">2011</span>, <span class="dv">2020</span>) <span class="co"># range 2011 - 2020</span></span>
<span id="cb75-395"><a href="#cb75-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-396"><a href="#cb75-396" aria-hidden="true" tabindex="-1"></a>model_Ugashik_1<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">auto.arima</span>(train_Ugashik_1<span class="fl">.3</span>)</span>
<span id="cb75-397"><a href="#cb75-397" aria-hidden="true" tabindex="-1"></a>model_Ugashik_1<span class="fl">.3</span></span>
<span id="cb75-398"><a href="#cb75-398" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-399"><a href="#cb75-399" aria-hidden="true" tabindex="-1"></a>model_Ugashik_1<span class="fl">.3</span>_out <span class="ot">&lt;-</span> <span class="fu">auto.arima</span>(train_Ugashik_1<span class="fl">.3</span>_out)</span>
<span id="cb75-400"><a href="#cb75-400" aria-hidden="true" tabindex="-1"></a>model_Ugashik_1<span class="fl">.3</span>_out</span>
<span id="cb75-401"><a href="#cb75-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-402"><a href="#cb75-402" aria-hidden="true" tabindex="-1"></a>model_Ugashik_2<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">auto.arima</span>(train_Ugashik_2<span class="fl">.2</span>)</span>
<span id="cb75-403"><a href="#cb75-403" aria-hidden="true" tabindex="-1"></a>model_Ugashik_2<span class="fl">.2</span></span>
<span id="cb75-404"><a href="#cb75-404" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-405"><a href="#cb75-405" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-406"><a href="#cb75-406" aria-hidden="true" tabindex="-1"></a><span class="fu">### Wood</span></span>
<span id="cb75-407"><a href="#cb75-407" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-410"><a href="#cb75-410" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-411"><a href="#cb75-411" aria-hidden="true" tabindex="-1"></a><span class="co">#Dylan's Code, need to speak on auto.arima model results</span></span>
<span id="cb75-412"><a href="#cb75-412" aria-hidden="true" tabindex="-1"></a><span class="co">#creating the training and testing periods for models</span></span>
<span id="cb75-413"><a href="#cb75-413" aria-hidden="true" tabindex="-1"></a>train.Wood_1<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">window</span>(Wood_1.<span class="fl">3.</span>ts, <span class="at">start =</span> <span class="dv">1963</span>, <span class="at">end =</span> <span class="dv">2010</span>)</span>
<span id="cb75-414"><a href="#cb75-414" aria-hidden="true" tabindex="-1"></a>test.Wood_1<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">window</span>(Wood_1.<span class="fl">3.</span>ts, <span class="at">start =</span> <span class="dv">2011</span>, <span class="at">end =</span> <span class="dv">2020</span>)</span>
<span id="cb75-415"><a href="#cb75-415" aria-hidden="true" tabindex="-1"></a>fit.Wood_1<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">auto.arima</span>(train.Wood_1<span class="fl">.3</span>)</span>
<span id="cb75-416"><a href="#cb75-416" aria-hidden="true" tabindex="-1"></a>fit.Wood_1<span class="fl">.3</span></span>
<span id="cb75-417"><a href="#cb75-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-418"><a href="#cb75-418" aria-hidden="true" tabindex="-1"></a>train.Wood_2<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">window</span>(Wood_2.<span class="fl">2.</span>ts, <span class="at">start =</span> <span class="dv">1963</span>, <span class="at">end =</span> <span class="dv">2010</span>)</span>
<span id="cb75-419"><a href="#cb75-419" aria-hidden="true" tabindex="-1"></a>test.Wood_2<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">window</span>(Wood_2.<span class="fl">2.</span>ts, <span class="at">start =</span> <span class="dv">2011</span>, <span class="at">end =</span> <span class="dv">2020</span>)</span>
<span id="cb75-420"><a href="#cb75-420" aria-hidden="true" tabindex="-1"></a>fit.Wood_2<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">auto.arima</span>(train.Wood_2<span class="fl">.2</span>)</span>
<span id="cb75-421"><a href="#cb75-421" aria-hidden="true" tabindex="-1"></a>fit.Wood_2<span class="fl">.2</span></span>
<span id="cb75-422"><a href="#cb75-422" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-423"><a href="#cb75-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-424"><a href="#cb75-424" aria-hidden="true" tabindex="-1"></a><span class="fu">### Kvichak</span></span>
<span id="cb75-425"><a href="#cb75-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-428"><a href="#cb75-428" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-429"><a href="#cb75-429" aria-hidden="true" tabindex="-1"></a><span class="co">#train and test predictions</span></span>
<span id="cb75-430"><a href="#cb75-430" aria-hidden="true" tabindex="-1"></a>train.Kvichak_1<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">window</span>(Kvichak_1.<span class="fl">3.</span>ts, <span class="at">start=</span> <span class="dv">1963</span>, <span class="at">end=</span><span class="dv">2010</span>)</span>
<span id="cb75-431"><a href="#cb75-431" aria-hidden="true" tabindex="-1"></a>test.Kvichak_1<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">window</span>(Kvichak_1.<span class="fl">3.</span>ts, <span class="at">start=</span> <span class="dv">2011</span>, <span class="at">end=</span> <span class="dv">2020</span>) </span>
<span id="cb75-432"><a href="#cb75-432" aria-hidden="true" tabindex="-1"></a>fit.Kvichak_1<span class="fl">.3</span> <span class="ot">&lt;-</span> forecast<span class="sc">::</span><span class="fu">auto.arima</span>(train.Kvichak_1<span class="fl">.3</span>)</span>
<span id="cb75-433"><a href="#cb75-433" aria-hidden="true" tabindex="-1"></a>fit.Kvichak_1<span class="fl">.3</span></span>
<span id="cb75-434"><a href="#cb75-434" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-435"><a href="#cb75-435" aria-hidden="true" tabindex="-1"></a>train.Kvichak_2<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">window</span>(Kvichak_2.<span class="fl">2.</span>ts, <span class="at">start=</span> <span class="dv">1963</span>, <span class="at">end=</span><span class="dv">2010</span>)</span>
<span id="cb75-436"><a href="#cb75-436" aria-hidden="true" tabindex="-1"></a>test.Kvichak_2<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">window</span>(Kvichak_2.<span class="fl">2.</span>ts, <span class="at">start=</span> <span class="dv">2011</span>, <span class="at">end=</span> <span class="dv">2020</span>)</span>
<span id="cb75-437"><a href="#cb75-437" aria-hidden="true" tabindex="-1"></a>fit.Kvichak_2<span class="fl">.2</span> <span class="ot">&lt;-</span> forecast<span class="sc">::</span><span class="fu">auto.arima</span>(train.Kvichak_2<span class="fl">.2</span>)</span>
<span id="cb75-438"><a href="#cb75-438" aria-hidden="true" tabindex="-1"></a>fit.Kvichak_2<span class="fl">.2</span></span>
<span id="cb75-439"><a href="#cb75-439" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-440"><a href="#cb75-440" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-441"><a href="#cb75-441" aria-hidden="true" tabindex="-1"></a><span class="fu"># Results</span></span>
<span id="cb75-442"><a href="#cb75-442" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-443"><a href="#cb75-443" aria-hidden="true" tabindex="-1"></a><span class="fu">## Plotting Best Fit Results and Determining Model Accuracy</span></span>
<span id="cb75-444"><a href="#cb75-444" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-445"><a href="#cb75-445" aria-hidden="true" tabindex="-1"></a><span class="fu">### Ugashik 1.3, Starting from 1980</span></span>
<span id="cb75-446"><a href="#cb75-446" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-449"><a href="#cb75-449" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-450"><a href="#cb75-450" aria-hidden="true" tabindex="-1"></a><span class="co">#Miranda's Code</span></span>
<span id="cb75-451"><a href="#cb75-451" aria-hidden="true" tabindex="-1"></a>fc_1<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">forecast</span>(model_Ugashik_1<span class="fl">.3</span>_out, <span class="at">h=</span><span class="dv">10</span>)</span>
<span id="cb75-452"><a href="#cb75-452" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-453"><a href="#cb75-453" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.ts</span>(Ugashik_1.<span class="fl">3.</span>ts) <span class="co"># check fit of model train on data from 1980 on</span></span>
<span id="cb75-454"><a href="#cb75-454" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">fitted</span>(model_Ugashik_1<span class="fl">.3</span>_out), <span class="at">col=</span><span class="st">"blue"</span>) <span class="co">#model seems to fit well</span></span>
<span id="cb75-455"><a href="#cb75-455" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-456"><a href="#cb75-456" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fc_1<span class="fl">.3</span>,<span class="at">ylab =</span> <span class="st">"log Abundance"</span>, <span class="at">xlab =</span> <span class="st">"Time"</span>)</span>
<span id="cb75-457"><a href="#cb75-457" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(test_Ugashik_1<span class="fl">.3</span>_out, <span class="at">pch=</span><span class="dv">19</span>, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb75-458"><a href="#cb75-458" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">fitted</span>(model_Ugashik_1<span class="fl">.3</span>_out), <span class="at">col=</span><span class="st">"blue"</span>)</span>
<span id="cb75-459"><a href="#cb75-459" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-460"><a href="#cb75-460" aria-hidden="true" tabindex="-1"></a>forecast<span class="sc">::</span><span class="fu">checkresiduals</span>(model_Ugashik_1<span class="fl">.3</span>_out) <span class="co"># looks better than 1.3 trained on 1960-2010</span></span>
<span id="cb75-461"><a href="#cb75-461" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">forecast</span>(model_Ugashik_1<span class="fl">.3</span>_out, <span class="at">h=</span><span class="dv">10</span>), test_Ugashik_1<span class="fl">.3</span>_out) <span class="co">#test accuracy </span></span>
<span id="cb75-462"><a href="#cb75-462" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-463"><a href="#cb75-463" aria-hidden="true" tabindex="-1"></a>The model itself seems to fit the data well based on the visual fit and the residuals.</span>
<span id="cb75-464"><a href="#cb75-464" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-465"><a href="#cb75-465" aria-hidden="true" tabindex="-1"></a>The model forecast centers around the mean of the train data, predicting that 2010 will drop which fits the first few actual data points well, but doesn't do as good of a job of predicting that the data from 2015-2020 look closer to the more recent years than further out (prior to 2005). Data are included in the confidence interval though which is great.</span>
<span id="cb75-466"><a href="#cb75-466" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-467"><a href="#cb75-467" aria-hidden="true" tabindex="-1"></a><span class="fu">### Ugashik 2.2</span></span>
<span id="cb75-468"><a href="#cb75-468" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-471"><a href="#cb75-471" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-472"><a href="#cb75-472" aria-hidden="true" tabindex="-1"></a>fc_2<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">forecast</span>(model_Ugashik_2<span class="fl">.2</span>, <span class="at">h=</span><span class="dv">10</span>)</span>
<span id="cb75-473"><a href="#cb75-473" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-474"><a href="#cb75-474" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fc_2<span class="fl">.2</span>,<span class="at">ylab =</span> <span class="st">"log Abundance"</span>, <span class="at">xlab =</span> <span class="st">"Time"</span>)</span>
<span id="cb75-475"><a href="#cb75-475" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(test_Ugashik_2<span class="fl">.2</span>, <span class="at">pch=</span><span class="dv">19</span>, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb75-476"><a href="#cb75-476" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">fitted</span>(model_Ugashik_2<span class="fl">.2</span>), <span class="at">col=</span><span class="st">"blue"</span>)</span>
<span id="cb75-477"><a href="#cb75-477" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-478"><a href="#cb75-478" aria-hidden="true" tabindex="-1"></a>forecast<span class="sc">::</span><span class="fu">checkresiduals</span>(model_Ugashik_2<span class="fl">.2</span>) </span>
<span id="cb75-479"><a href="#cb75-479" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">forecast</span>(model_Ugashik_2<span class="fl">.2</span>, <span class="at">h=</span><span class="dv">10</span>), test_Ugashik_2<span class="fl">.2</span>) <span class="co">#test accuracy</span></span>
<span id="cb75-480"><a href="#cb75-480" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-481"><a href="#cb75-481" aria-hidden="true" tabindex="-1"></a>The model fits the timeseries train data pretty well, matching the overall change in curve. The residuals show the ACF plot has 1 significant lag reflecting the ARIMA (1,0,0) model, the histogram is fairly centered as expected, and model fails to reject Ljung-Box test.</span>
<span id="cb75-482"><a href="#cb75-482" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-483"><a href="#cb75-483" aria-hidden="true" tabindex="-1"></a>Model forecast doesn't look great. The forecast flatlines while the real data from 2011-2020 have much higher variance. This reflects the high AICc from the model. But the data are contained within the predicted confidence interval which is good. <span class="sc">\#</span>## Wood 2.2</span>
<span id="cb75-484"><a href="#cb75-484" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-487"><a href="#cb75-487" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-488"><a href="#cb75-488" aria-hidden="true" tabindex="-1"></a>pred.Wood_2<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit.Wood_2<span class="fl">.2</span>, <span class="at">h =</span> <span class="dv">10</span>)</span>
<span id="cb75-489"><a href="#cb75-489" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pred.Wood_2<span class="fl">.2</span>,<span class="at">ylab =</span> <span class="st">"log Abundance"</span>, <span class="at">xlab =</span> <span class="st">"Time"</span>)</span>
<span id="cb75-490"><a href="#cb75-490" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(test.Wood_2<span class="fl">.2</span>, <span class="at">pch=</span><span class="dv">19</span>, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb75-491"><a href="#cb75-491" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">fitted</span>(fit.Wood_2<span class="fl">.2</span>), <span class="at">col=</span><span class="st">"blue"</span>)</span>
<span id="cb75-492"><a href="#cb75-492" aria-hidden="true" tabindex="-1"></a><span class="co">#the actual observations do fall within the 80% prediction interval</span></span>
<span id="cb75-493"><a href="#cb75-493" aria-hidden="true" tabindex="-1"></a><span class="co">#This data is treated as white noise with the ARIMA(0,0,0) model so </span></span>
<span id="cb75-494"><a href="#cb75-494" aria-hidden="true" tabindex="-1"></a><span class="co">#I imagine the prediction intervals are tied very closely to the variance </span></span>
<span id="cb75-495"><a href="#cb75-495" aria-hidden="true" tabindex="-1"></a><span class="co">#of the residuals themselves.</span></span>
<span id="cb75-496"><a href="#cb75-496" aria-hidden="true" tabindex="-1"></a>forecast<span class="sc">::</span><span class="fu">checkresiduals</span>(fit.Wood_2<span class="fl">.2</span>) </span>
<span id="cb75-497"><a href="#cb75-497" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">forecast</span>(fit.Wood_2<span class="fl">.2</span>, <span class="at">h =</span> <span class="dv">10</span>), test.Wood_2<span class="fl">.2</span>)</span>
<span id="cb75-498"><a href="#cb75-498" aria-hidden="true" tabindex="-1"></a><span class="co">#the RMSE done manually matches with the RMSE value that is found by the </span></span>
<span id="cb75-499"><a href="#cb75-499" aria-hidden="true" tabindex="-1"></a><span class="co">#model in row 2, column 2. This must be how the model does when compared to the </span></span>
<span id="cb75-500"><a href="#cb75-500" aria-hidden="true" tabindex="-1"></a><span class="co">#test data. So we have RMSE = 0.731</span></span>
<span id="cb75-501"><a href="#cb75-501" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-502"><a href="#cb75-502" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-503"><a href="#cb75-503" aria-hidden="true" tabindex="-1"></a>The model fit the training data well as indicated by the Box test's failure to reject the null hypothesis. The actual observations do fall within the 80% prediction interval This data is treated as white noise with the ARIMA(0,0,0) model so we predict the prediction intervals are tied very closely to the variance of the residuals themselves.The RMSE = 0.731</span>
<span id="cb75-504"><a href="#cb75-504" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-505"><a href="#cb75-505" aria-hidden="true" tabindex="-1"></a><span class="fu">### Wood 1.3</span></span>
<span id="cb75-506"><a href="#cb75-506" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-509"><a href="#cb75-509" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-510"><a href="#cb75-510" aria-hidden="true" tabindex="-1"></a>pred.Wood_1<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit.Wood_1<span class="fl">.3</span>, <span class="at">h =</span> <span class="dv">10</span>)</span>
<span id="cb75-511"><a href="#cb75-511" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-512"><a href="#cb75-512" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pred.Wood_1<span class="fl">.3</span>,<span class="at">ylab =</span> <span class="st">"log Abundance"</span>, <span class="at">xlab =</span> <span class="st">"Time"</span>)</span>
<span id="cb75-513"><a href="#cb75-513" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(test.Wood_1<span class="fl">.3</span>, <span class="at">pch=</span><span class="dv">19</span>, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb75-514"><a href="#cb75-514" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">fitted</span>(fit.Wood_1<span class="fl">.3</span>), <span class="at">col=</span><span class="st">"blue"</span>) </span>
<span id="cb75-515"><a href="#cb75-515" aria-hidden="true" tabindex="-1"></a><span class="co">#we see that the prediction intervals widen as the forecast moves forward</span></span>
<span id="cb75-516"><a href="#cb75-516" aria-hidden="true" tabindex="-1"></a><span class="co">#likely due to the autocorrelation of the errors, because this is an MA(1) model,</span></span>
<span id="cb75-517"><a href="#cb75-517" aria-hidden="true" tabindex="-1"></a><span class="co">#which the model has to estimate with each successive prediction. The fitted points</span></span>
<span id="cb75-518"><a href="#cb75-518" aria-hidden="true" tabindex="-1"></a><span class="co">#are a flat line again because this is an MA(1) model, we would write the model as</span></span>
<span id="cb75-519"><a href="#cb75-519" aria-hidden="true" tabindex="-1"></a><span class="co"># Xt = Xt-1 + error. When we fitted a model to the entire dataset, auto.arima() </span></span>
<span id="cb75-520"><a href="#cb75-520" aria-hidden="true" tabindex="-1"></a><span class="co">#selected an ARIMA(0,1,1) with drift, however with just the training data auto.arima() </span></span>
<span id="cb75-521"><a href="#cb75-521" aria-hidden="true" tabindex="-1"></a><span class="co">#selected an ARIMA(0,1,1) because the model does not have drift, the predictions stay as a flat line</span></span>
<span id="cb75-522"><a href="#cb75-522" aria-hidden="true" tabindex="-1"></a><span class="co"># rather than having a trend.</span></span>
<span id="cb75-523"><a href="#cb75-523" aria-hidden="true" tabindex="-1"></a><span class="co">#residuals.3 &lt;- test.Wood_1.3[1:10] - pred.Wood_1.3$mean[1:10]</span></span>
<span id="cb75-524"><a href="#cb75-524" aria-hidden="true" tabindex="-1"></a><span class="co">#sqrt(mean(residuals.3^2))</span></span>
<span id="cb75-525"><a href="#cb75-525" aria-hidden="true" tabindex="-1"></a>forecast<span class="sc">::</span><span class="fu">checkresiduals</span>(fit.Wood_1<span class="fl">.3</span>) </span>
<span id="cb75-526"><a href="#cb75-526" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="fu">forecast</span>(fit.Wood_1<span class="fl">.3</span>, <span class="at">h =</span> <span class="dv">10</span>), test.Wood_1<span class="fl">.3</span>)</span>
<span id="cb75-527"><a href="#cb75-527" aria-hidden="true" tabindex="-1"></a><span class="co">#the Root Mean Squared Error for this model is 0.532. This value is less</span></span>
<span id="cb75-528"><a href="#cb75-528" aria-hidden="true" tabindex="-1"></a><span class="co">#than the value for the Wood_2.2 model. This is a bit surprising as they both</span></span>
<span id="cb75-529"><a href="#cb75-529" aria-hidden="true" tabindex="-1"></a><span class="co">#put a straight line on the graph for predictions. These values indicate that </span></span>
<span id="cb75-530"><a href="#cb75-530" aria-hidden="true" tabindex="-1"></a><span class="co">#the model for wood.3 was more accurate. The returns of fish that spent less time in fresh</span></span>
<span id="cb75-531"><a href="#cb75-531" aria-hidden="true" tabindex="-1"></a><span class="co">#water and longer in the ocean were more accurately predicted than of the fish who spent</span></span>
<span id="cb75-532"><a href="#cb75-532" aria-hidden="true" tabindex="-1"></a><span class="co">#two years in both freshwater and the ocean.</span></span>
<span id="cb75-533"><a href="#cb75-533" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-534"><a href="#cb75-534" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-535"><a href="#cb75-535" aria-hidden="true" tabindex="-1"></a>Again we see that the model fit the training dataset well. The box test fails to reject the null hypotheis. We see that the prediction intervals widen as the forecast moves forward likely due to the autocorrelation of the errors, because this is an MA(1) model, which the model has to estimate with each successive prediction. The fitted points are a flat line again because this is an MA(1) model, we would write the model as Xt = Xt-1 + error. When we fitted a model to the entire dataset, auto.arima() selected an ARIMA(0,1,1) with drift, however with just the training data auto.arima() selected an ARIMA(0,1,1) because the model does not have drift, the predictions stay as a flat line rather than having a trend.</span>
<span id="cb75-536"><a href="#cb75-536" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-537"><a href="#cb75-537" aria-hidden="true" tabindex="-1"></a>the Root Mean Squared Error for this model is 0.532. This value is less than the value for the Wood_2.2 model. This is a bit surprising as they both put a straight line on the graph for predictions. These values indicate that the model for wood_1.3 was more accurate at predicting future observations. The returns of fish that spent less time in fresh water and longer in the ocean were more accurately predicted than of the fish who spent two years in both freshwater and the ocean.</span>
<span id="cb75-538"><a href="#cb75-538" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-539"><a href="#cb75-539" aria-hidden="true" tabindex="-1"></a><span class="fu">### Kvichak 2.2</span></span>
<span id="cb75-540"><a href="#cb75-540" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-543"><a href="#cb75-543" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-544"><a href="#cb75-544" aria-hidden="true" tabindex="-1"></a>pred.kvi2 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit.Kvichak_2<span class="fl">.2</span>, <span class="at">h=</span><span class="dv">10</span>)</span>
<span id="cb75-545"><a href="#cb75-545" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-546"><a href="#cb75-546" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pred.kvi2,<span class="at">ylab=</span> <span class="st">"log Abundance"</span>, <span class="at">xlab =</span><span class="st">"Time"</span>)</span>
<span id="cb75-547"><a href="#cb75-547" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(test.Kvichak_2<span class="fl">.2</span>, <span class="at">pch=</span><span class="dv">19</span>, <span class="at">col =</span><span class="st">"red"</span>)</span>
<span id="cb75-548"><a href="#cb75-548" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">fitted</span>(fit.Kvichak_2<span class="fl">.2</span>), <span class="at">col=</span><span class="st">"blue"</span>)</span>
<span id="cb75-549"><a href="#cb75-549" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-550"><a href="#cb75-550" aria-hidden="true" tabindex="-1"></a>forecast<span class="sc">::</span><span class="fu">checkresiduals</span>(fit.Kvichak_2<span class="fl">.2</span>)</span>
<span id="cb75-551"><a href="#cb75-551" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(pred.kvi2, test.Kvichak_2<span class="fl">.2</span>)</span>
<span id="cb75-552"><a href="#cb75-552" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb75-553"><a href="#cb75-553" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-554"><a href="#cb75-554" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-555"><a href="#cb75-555" aria-hidden="true" tabindex="-1"></a>Here we see the cyclic nature of the data reflected in the residual's ACF plot and the rejection of the Box test. This may have affected the model's ability to predict. The RMSE = 2.088. The actual data points fell outside of the prediction intervals with this model. We observe the same straight line provided by the MA() model but there was more variance in this data which corresponds to the poor prediction performance <span class="sc">\#</span>## Kvichak 1.3</span>
<span id="cb75-556"><a href="#cb75-556" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-559"><a href="#cb75-559" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb75-560"><a href="#cb75-560" aria-hidden="true" tabindex="-1"></a><span class="co">#chooses same exact model as the full dataset model</span></span>
<span id="cb75-561"><a href="#cb75-561" aria-hidden="true" tabindex="-1"></a>pred.kvi3 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit.Kvichak_1<span class="fl">.3</span>, <span class="at">h=</span><span class="dv">10</span>)</span>
<span id="cb75-562"><a href="#cb75-562" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-563"><a href="#cb75-563" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pred.kvi3, <span class="at">ylab=</span> <span class="st">"log Abundance"</span>, <span class="at">xlab =</span><span class="st">"Time"</span>)</span>
<span id="cb75-564"><a href="#cb75-564" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(test.Kvichak_1<span class="fl">.3</span>, <span class="at">pch=</span><span class="dv">19</span>, <span class="at">col =</span><span class="st">"red"</span> ) </span>
<span id="cb75-565"><a href="#cb75-565" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">fitted</span>(fit.Kvichak_1<span class="fl">.3</span>), <span class="at">col=</span><span class="st">"blue"</span>)</span>
<span id="cb75-566"><a href="#cb75-566" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-567"><a href="#cb75-567" aria-hidden="true" tabindex="-1"></a>forecast<span class="sc">::</span><span class="fu">checkresiduals</span>(fit.Kvichak_1<span class="fl">.3</span>) </span>
<span id="cb75-568"><a href="#cb75-568" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(pred.kvi3, test.Kvichak_1<span class="fl">.3</span>)</span>
<span id="cb75-569"><a href="#cb75-569" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb75-570"><a href="#cb75-570" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb75-571"><a href="#cb75-571" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-572"><a href="#cb75-572" aria-hidden="true" tabindex="-1"></a>The model fit the training data well again based on the failure to reject the Box test and did a good job forecasting future observation. The RMSE = 0.65 for this forecast's accuracy, we see the prediction line with a positive trend which results because the model is ARIMA(0,1,1) with drift. Due to the smaller amount of variance in this data set the points fall much closer to the straight line prediction. Again we see that returns for fish that spent longer in the ocean were more accurately predicted in this system.</span>
<span id="cb75-573"><a href="#cb75-573" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-574"><a href="#cb75-574" aria-hidden="true" tabindex="-1"></a><span class="fu"># Discussion</span></span>
<span id="cb75-575"><a href="#cb75-575" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-576"><a href="#cb75-576" aria-hidden="true" tabindex="-1"></a>We examined if fish which spent longer in the ocean were more or less predictable than fish of the same age which spent less time in the ocean. We found in the Wood and Kvichak systems that models trained on data for four year old fish which spent longer in the ocean (3 years vs 2 years) made more accurate forecasts as indicated by smaller RMSE values.</span>
<span id="cb75-577"><a href="#cb75-577" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-578"><a href="#cb75-578" aria-hidden="true" tabindex="-1"></a>The predictions for the Wood and Kvichak systems were straight line predictions as the models that were selected either only had a MA component or, in the case of the Wood 2.2 age group where the observations were considered white noise already, had neither and AR or MA component. In the Ugashik system, the models fitted both had AR components and thus we see the predicted mean line has a bit of structure to it as each prediction relies on the value of the previous prediction.</span>
<span id="cb75-579"><a href="#cb75-579" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-580"><a href="#cb75-580" aria-hidden="true" tabindex="-1"></a>We found that in the Ugashik system, removing the data prior to 1980 to remove increased variance in the data improved predictions from the model. This could be a good step to investigate doing for the other river systems as well which also show some unusual activity prior to 1980.</span>
<span id="cb75-581"><a href="#cb75-581" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-582"><a href="#cb75-582" aria-hidden="true" tabindex="-1"></a><span class="fu"># Description of each team member's contributions</span></span>
<span id="cb75-583"><a href="#cb75-583" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-584"><a href="#cb75-584" aria-hidden="true" tabindex="-1"></a>Dylan wrote the code for the Wood and Kvichak regions, Miranda wrote the code for the Ugashik region, and Eric and Dylan wrote sections of the report with input continued from Miranda.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>